const words_en_adverbs = [
  { en:"abroad", jp:["海外で"], pos:"副詞", category:"場所" },
  { en:"absolutely", jp:["完全に","絶対に"], pos:"副詞", category:"程度" },
  { en:"academically", jp:["学問的に"], pos:"副詞", category:"学習" },
  { en:"accordingly", jp:["それに応じて"], pos:"副詞", category:"会話" },
  { en:"accurately", jp:["正確に"], pos:"副詞", category:"学習" },
  { en:"actively", jp:["積極的に"], pos:"副詞", category:"行動" },
  { en:"additionally", jp:["さらに"], pos:"副詞", category:"会話" },
  { en:"adequately", jp:["十分に"], pos:"副詞", category:"程度" },
  { en:"apparently", jp:["どうやら"], pos:"副詞", category:"思考" },
  { en:"appropriately", jp:["適切に"], pos:"副詞", category:"程度" },
  { en:"automatically", jp:["自動的に"], pos:"副詞", category:"行動" },

  { en:"basically", jp:["基本的に"], pos:"副詞", category:"会話" },
  { en:"briefly", jp:["簡潔に"], pos:"副詞", category:"会話" },

  { en:"carefully", jp:["注意深く"], pos:"副詞", category:"行動" },
  { en:"certainly", jp:["確かに"], pos:"副詞", category:"思考" },
  { en:"clearly", jp:["明らかに"], pos:"副詞", category:"思考" },
  { en:"closely", jp:["綿密に","密接に"], pos:"副詞", category:"程度" },
  { en:"commonly", jp:["一般に"], pos:"副詞", category:"抽象" },
  { en:"completely", jp:["完全に"], pos:"副詞", category:"程度" },
  { en:"consequently", jp:["その結果"], pos:"副詞", category:"会話" },
  { en:"constantly", jp:["絶えず"], pos:"副詞", category:"時間" },
  { en:"currently", jp:["現在"], pos:"副詞", category:"時間" },

  { en:"definitely", jp:["確実に"], pos:"副詞", category:"思考" },
  { en:"deliberately", jp:["故意に"], pos:"副詞", category:"行動" },
  { en:"directly", jp:["直接"], pos:"副詞", category:"程度" },

  { en:"effectively", jp:["効果的に"], pos:"副詞", category:"程度" },
  { en:"efficiently", jp:["効率的に"], pos:"副詞", category:"程度" },
  { en:"emotionally", jp:["感情的に"], pos:"副詞", category:"感情" },
  { en:"entirely", jp:["完全に"], pos:"副詞", category:"程度" },
  { en:"equally", jp:["同様に"], pos:"副詞", category:"程度" },
  { en:"especially", jp:["特に"], pos:"副詞", category:"程度" },
  { en:"essentially", jp:["本質的に"], pos:"副詞", category:"思考" },
  { en:"eventually", jp:["最終的に"], pos:"副詞", category:"時間" },
  { en:"exactly", jp:["正確に","ちょうど"], pos:"副詞", category:"学習" },
  { en:"extensively", jp:["広範囲に"], pos:"副詞", category:"程度" },
  { en:"externally", jp:["外部に"], pos:"副詞", category:"場所" },

  { en:"fairly", jp:["かなり"], pos:"副詞", category:"程度" },
  { en:"finally", jp:["ついに","最後に"], pos:"副詞", category:"時間" },
  { en:"frequently", jp:["頻繁に"], pos:"副詞", category:"時間" },
  { en:"fully", jp:["十分に","完全に"], pos:"副詞", category:"程度" },
  { en:"fundamentally", jp:["根本的に"], pos:"副詞", category:"思考" },

  { en:"generally", jp:["一般に"], pos:"副詞", category:"抽象" },
  { en:"gradually", jp:["徐々に"], pos:"副詞", category:"時間" },
  { en:"greatly", jp:["大いに"], pos:"副詞", category:"程度" },

  { en:"hardly", jp:["ほとんど〜ない"], pos:"副詞", category:"程度" },
  { en:"highly", jp:["非常に","高度に"], pos:"副詞", category:"程度" },
  { en:"historically", jp:["歴史的に"], pos:"副詞", category:"時間" },

  { en:"ideally", jp:["理想的には"], pos:"副詞", category:"思考" },
  { en:"immediately", jp:["すぐに"], pos:"副詞", category:"時間" },
  { en:"increasingly", jp:["ますます"], pos:"副詞", category:"変化" },
  { en:"independently", jp:["独立して"], pos:"副詞", category:"状態" },
  { en:"inevitably", jp:["必然的に"], pos:"副詞", category:"思考" },
  { en:"initially", jp:["最初は"], pos:"副詞", category:"時間" },
  { en:"internally", jp:["内部で"], pos:"副詞", category:"場所" },
  { en:"internationally", jp:["国際的に"], pos:"副詞", category:"社会" },

  { en:"largely", jp:["主に"], pos:"副詞", category:"程度" },
  { en:"legally", jp:["法律上"], pos:"副詞", category:"社会" },
  { en:"likely", jp:["おそらく"], pos:"副詞", category:"思考" },
  { en:"literally", jp:["文字通り"], pos:"副詞", category:"学習" },
  { en:"logically", jp:["論理的に"], pos:"副詞", category:"思考" },

  { en:"mainly", jp:["主に"], pos:"副詞", category:"程度" },
  { en:"meanwhile", jp:["その間に"], pos:"副詞", category:"時間" },
  { en:"merely", jp:["単に"], pos:"副詞", category:"程度" },
  { en:"naturally", jp:["当然"], pos:"副詞", category:"思考" },
  { en:"necessarily", jp:["必ずしも"], pos:"副詞", category:"思考" },
  { en:"negatively", jp:["否定的に"], pos:"副詞", category:"感情" },
  { en:"normally", jp:["通常"], pos:"副詞", category:"時間" },
  { en:"noticeably", jp:["目立って"], pos:"副詞", category:"程度" },

  { en:"obviously", jp:["明らかに"], pos:"副詞", category:"思考" },
  { en:"officially", jp:["公式に"], pos:"副詞", category:"社会" },
  { en:"occasionally", jp:["時々"], pos:"副詞", category:"時間" },
  { en:"originally", jp:["もともと"], pos:"副詞", category:"時間" },
  { en:"overall", jp:["全体として"], pos:"副詞", category:"抽象" },

  { en:"particularly", jp:["特に"], pos:"副詞", category:"程度" },
  { en:"partly", jp:["部分的に"], pos:"副詞", category:"程度" },
  { en:"perfectly", jp:["完全に"], pos:"副詞", category:"程度" },
  { en:"permanently", jp:["永久に"], pos:"副詞", category:"時間" },
  { en:"personally", jp:["個人的に"], pos:"副詞", category:"会話" },
  { en:"physically", jp:["身体的に"], pos:"副詞", category:"体" },
  { en:"politically", jp:["政治的に"], pos:"副詞", category:"社会" },
  { en:"positively", jp:["前向きに"], pos:"副詞", category:"感情" },
  { en:"potentially", jp:["潜在的に"], pos:"副詞", category:"抽象" },
  { en:"precisely", jp:["正確に"], pos:"副詞", category:"学習" },
  { en:"previously", jp:["以前に"], pos:"副詞", category:"時間" },
  { en:"primarily", jp:["主として"], pos:"副詞", category:"程度" },
  { en:"probably", jp:["おそらく"], pos:"副詞", category:"思考" },
  { en:"properly", jp:["適切に"], pos:"副詞", category:"程度" },
  { en:"psychologically", jp:["心理的に"], pos:"副詞", category:"感情" },
  { en:"publicly", jp:["公に"], pos:"副詞", category:"社会" },

  { en:"rapidly", jp:["急速に"], pos:"副詞", category:"時間" },
  { en:"rarely", jp:["めったに〜ない"], pos:"副詞", category:"時間" },
  { en:"reasonably", jp:["合理的に","かなり"], pos:"副詞", category:"思考" },
  { en:"recently", jp:["最近"], pos:"副詞", category:"時間" },
  { en:"regardless", jp:["関係なく"], pos:"副詞", category:"抽象" },
  { en:"regularly", jp:["定期的に"], pos:"副詞", category:"時間" },
  { en:"relatively", jp:["比較的"], pos:"副詞", category:"程度" },
  { en:"remarkably", jp:["著しく"], pos:"副詞", category:"程度" },
  { en:"roughly", jp:["おおよそ"], pos:"副詞", category:"数字" },

  { en:"seriously", jp:["真剣に","深刻に"], pos:"副詞", category:"感情" },
  { en:"significantly", jp:["著しく","重要なことに"], pos:"副詞", category:"程度" },
  { en:"similarly", jp:["同様に"], pos:"副詞", category:"会話" },
  { en:"slightly", jp:["わずかに"], pos:"副詞", category:"程度" },
  { en:"socially", jp:["社会的に"], pos:"副詞", category:"社会" },
  { en:"specifically", jp:["具体的に"], pos:"副詞", category:"会話" },
  { en:"steadily", jp:["着実に"], pos:"副詞", category:"変化" },
  { en:"strongly", jp:["強く"], pos:"副詞", category:"程度" },
  { en:"subsequently", jp:["その後"], pos:"副詞", category:"時間" },
  { en:"substantially", jp:["かなり"], pos:"副詞", category:"程度" },
  { en:"suddenly", jp:["突然"], pos:"副詞", category:"時間" },
  { en:"sufficiently", jp:["十分に"], pos:"副詞", category:"程度" },
  { en:"surprisingly", jp:["驚くほど"], pos:"副詞", category:"感情" },

  { en:"technically", jp:["技術的に"], pos:"副詞", category:"学習" },
  { en:"temporarily", jp:["一時的に"], pos:"副詞", category:"時間" },
  { en:"therefore", jp:["それゆえに"], pos:"副詞", category:"会話" },
  { en:"thoroughly", jp:["徹底的に"], pos:"副詞", category:"程度" },
  { en:"typically", jp:["典型的に"], pos:"副詞", category:"抽象" },

  { en:"ultimately", jp:["最終的に"], pos:"副詞", category:"時間" },
  { en:"unavoidably", jp:["避けられず"], pos:"副詞", category:"思考" },
  { en:"universally", jp:["普遍的に"], pos:"副詞", category:"抽象" },
  { en:"usually", jp:["通常"], pos:"副詞", category:"時間" },

  { en:"virtually", jp:["事実上"], pos:"副詞", category:"抽象" },

  { en:"widely", jp:["広く"], pos:"副詞", category:"程度" }
];