const words_de_nouns = [
  { de:"der Abend", en:["evening"], jp:["夕方","晩"], pos:"名詞", category:"時間" },
  { de:"das Abenteuer", en:["adventure"], jp:["冒険"], pos:"名詞", category:"抽象" },
  { de:"der Anfang", en:["beginning"], jp:["始まり"], pos:"名詞", category:"時間" },
  { de:"die Antwort", en:["answer"], jp:["答え"], pos:"名詞", category:"学習" },
  { de:"der Apfel", en:["apple"], jp:["りんご"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Arm", en:["arm"], jp:["腕"], pos:"名詞", category:"体" },
  { de:"der Arzt", en:["doctor"], jp:["医者"], pos:"名詞", category:"人" },
  { de:"das Auge", en:["eye"], jp:["目"], pos:"名詞", category:"体" },
  { de:"das Auto", en:["car"], jp:["車"], pos:"名詞", category:"交通" },

  { de:"die Bäckerei", en:["bakery"], jp:["パン屋"], pos:"名詞", category:"場所" },
  { de:"der Bahnhof", en:["station"], jp:["駅"], pos:"名詞", category:"交通" },
  { de:"der Ball", en:["ball"], jp:["ボール"], pos:"名詞", category:"物" },
  { de:"die Banane", en:["banana"], jp:["バナナ"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"die Bank", en:["bank","bench"], jp:["銀行","ベンチ"], pos:"名詞", category:"場所" },
  { de:"das Badezimmer", en:["bathroom"], jp:["浴室"], pos:"名詞", category:"家・家具" },
  { de:"das Bein", en:["leg"], jp:["脚"], pos:"名詞", category:"体" },
  { de:"das Bett", en:["bed"], jp:["ベッド"], pos:"名詞", category:"家・家具" },
  { de:"das Bild", en:["picture","image"], jp:["絵","画像"], pos:"名詞", category:"物" },
  { de:"die Blume", en:["flower"], jp:["花"], pos:"名詞", category:"自然" },
  { de:"das Brot", en:["bread"], jp:["パン"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Bruder", en:["brother"], jp:["兄弟"], pos:"名詞", category:"人" },
  { de:"das Buch", en:["book"], jp:["本"], pos:"名詞", category:"学習" },
  { de:"der Bus", en:["bus"], jp:["バス"], pos:"名詞", category:"交通" },

  { de:"das Café", en:["cafe"], jp:["カフェ"], pos:"名詞", category:"場所" },
  { de:"der Computer", en:["computer"], jp:["コンピューター"], pos:"名詞", category:"物" },

  { de:"das Dach", en:["roof"], jp:["屋根"], pos:"名詞", category:"家・家具" },
  { de:"die Dame", en:["lady"], jp:["女性"], pos:"名詞", category:"人" },
  { de:"das Datum", en:["date"], jp:["日付"], pos:"名詞", category:"時間" },
  { de:"das Dorf", en:["village"], jp:["村"], pos:"名詞", category:"場所" },
  { de:"die Dusche", en:["shower"], jp:["シャワー"], pos:"名詞", category:"家・家具" },

  { de:"das Ei", en:["egg"], jp:["卵"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"die E-Mail", en:["email"], jp:["メール"], pos:"名詞", category:"会話" },
  { de:"das Ende", en:["end"], jp:["終わり"], pos:"名詞", category:"時間" },
  { de:"die Eltern", en:["parents"], jp:["両親"], pos:"名詞", category:"人" },
  { de:"das Essen", en:["food","meal"], jp:["食べ物","食事"], pos:"名詞", category:"食べ物・飲み物" },

  { de:"das Fahrrad", en:["bicycle"], jp:["自転車"], pos:"名詞", category:"交通" },
  { de:"die Familie", en:["family"], jp:["家族"], pos:"名詞", category:"人" },
  { de:"das Fenster", en:["window"], jp:["窓"], pos:"名詞", category:"家・家具" },
  { de:"der Film", en:["movie"], jp:["映画"], pos:"名詞", category:"芸術" },
  { de:"die Firma", en:["company"], jp:["会社"], pos:"名詞", category:"社会" },
  { de:"die Flasche", en:["bottle"], jp:["ボトル"], pos:"名詞", category:"物" },
  { de:"das Fleisch", en:["meat"], jp:["肉"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Flug", en:["flight"], jp:["飛行"], pos:"名詞", category:"交通" },
  { de:"der Freund", en:["friend"], jp:["男友達"], pos:"名詞", category:"人" },
  { de:"die Freundin", en:["friend"], jp:["女友達"], pos:"名詞", category:"人" },
  { de:"das Frühstück", en:["breakfast"], jp:["朝食"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Fuß", en:["foot"], jp:["足"], pos:"名詞", category:"体" },

  { de:"der Garten", en:["garden"], jp:["庭"], pos:"名詞", category:"自然" },
  { de:"das Geburtsdatum", en:["birth date"], jp:["生年月日"], pos:"名詞", category:"時間" },
  { de:"das Gemüse", en:["vegetable"], jp:["野菜"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"das Geschenk", en:["gift"], jp:["プレゼント"], pos:"名詞", category:"物" },
  { de:"das Gespräch", en:["conversation"], jp:["会話"], pos:"名詞", category:"会話" },
  { de:"das Getränk", en:["drink"], jp:["飲み物"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"das Glas", en:["glass"], jp:["コップ","ガラス"], pos:"名詞", category:"物" },
  { de:"das Glück", en:["luck","happiness"], jp:["幸運","幸福"], pos:"名詞", category:"感情" },
  { de:"die Großmutter", en:["grandmother"], jp:["祖母"], pos:"名詞", category:"人" },
  { de:"der Großvater", en:["grandfather"], jp:["祖父"], pos:"名詞", category:"人" },

  { de:"die Hand", en:["hand"], jp:["手"], pos:"名詞", category:"体" },
  { de:"das Handy", en:["mobile phone"], jp:["携帯電話"], pos:"名詞", category:"物" },
  { de:"das Haus", en:["house"], jp:["家"], pos:"名詞", category:"家・家具" },
  { de:"der Herbst", en:["autumn"], jp:["秋"], pos:"名詞", category:"時間" },
  { de:"das Herz", en:["heart"], jp:["心臓","心"], pos:"名詞", category:"体" },
  { de:"der Himmel", en:["sky"], jp:["空"], pos:"名詞", category:"自然" },
  { de:"das Hobby", en:["hobby"], jp:["趣味"], pos:"名詞", category:"抽象" },
  { de:"der Hund", en:["dog"], jp:["犬"], pos:"名詞", category:"自然" },

  { de:"die Idee", en:["idea"], jp:["考え"], pos:"名詞", category:"思考" },
  { de:"die Insel", en:["island"], jp:["島"], pos:"名詞", category:"場所" },

  { de:"das Jahr", en:["year"], jp:["年"], pos:"名詞", category:"時間" },
  { de:"der Januar", en:["January"], jp:["1月"], pos:"名詞", category:"時間" },
  { de:"der Juli", en:["July"], jp:["7月"], pos:"名詞", category:"時間" },
  { de:"der Juni", en:["June"], jp:["6月"], pos:"名詞", category:"時間" },

  { de:"der Kaffee", en:["coffee"], jp:["コーヒー"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"die Kamera", en:["camera"], jp:["カメラ"], pos:"名詞", category:"物" },
  { de:"das Kind", en:["child"], jp:["子ども"], pos:"名詞", category:"人" },
  { de:"das Kino", en:["cinema"], jp:["映画館"], pos:"名詞", category:"場所" },
  { de:"die Kirche", en:["church"], jp:["教会"], pos:"名詞", category:"場所" },
  { de:"die Klasse", en:["class"], jp:["クラス"], pos:"名詞", category:"学習" },
  { de:"das Kleid", en:["dress"], jp:["ワンピース"], pos:"名詞", category:"物" },
  { de:"das Klima", en:["climate"], jp:["気候"], pos:"名詞", category:"自然" },
  { de:"die Küche", en:["kitchen"], jp:["台所"], pos:"名詞", category:"家・家具" },

  { de:"die Lampe", en:["lamp"], jp:["ランプ"], pos:"名詞", category:"家・家具" },
  { de:"das Land", en:["country"], jp:["国"], pos:"名詞", category:"場所" },
  { de:"die Lehrerin", en:["teacher"], jp:["女性教師"], pos:"名詞", category:"人" },
  { de:"der Lehrer", en:["teacher"], jp:["男性教師"], pos:"名詞", category:"人" },
  { de:"das Leben", en:["life"], jp:["人生","命"], pos:"名詞", category:"抽象" },
  { de:"das Licht", en:["light"], jp:["光"], pos:"名詞", category:"自然" },
  { de:"das Lied", en:["song"], jp:["歌"], pos:"名詞", category:"芸術" },
  { de:"die Liebe", en:["love"], jp:["愛"], pos:"名詞", category:"感情" },
  { de:"die Luft", en:["air"], jp:["空気"], pos:"名詞", category:"自然" },

  { de:"der Mann", en:["man"], jp:["男性"], pos:"名詞", category:"人" },
  { de:"der Markt", en:["market"], jp:["市場"], pos:"名詞", category:"場所" },
  { de:"die Milch", en:["milk"], jp:["牛乳"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Mittag", en:["noon"], jp:["正午"], pos:"名詞", category:"時間" },
  { de:"der Monat", en:["month"], jp:["月"], pos:"名詞", category:"時間" },
  { de:"der Morgen", en:["morning"], jp:["朝"], pos:"名詞", category:"時間" },
  { de:"die Mutter", en:["mother"], jp:["母"], pos:"名詞", category:"人" },
  { de:"die Musik", en:["music"], jp:["音楽"], pos:"名詞", category:"芸術" },

  { de:"die Nacht", en:["night"], jp:["夜"], pos:"名詞", category:"時間" },
  { de:"der Name", en:["name"], jp:["名前"], pos:"名詞", category:"会話" },
  { de:"die Nase", en:["nose"], jp:["鼻"], pos:"名詞", category:"体" },
  { de:"die Natur", en:["nature"], jp:["自然"], pos:"名詞", category:"自然" },

  { de:"das Ohr", en:["ear"], jp:["耳"], pos:"名詞", category:"体" },
  { de:"die Orange", en:["orange"], jp:["オレンジ"], pos:"名詞", category:"食べ物・飲み物" },

  { de:"das Papier", en:["paper"], jp:["紙"], pos:"名詞", category:"物" },
  { de:"der Park", en:["park"], jp:["公園"], pos:"名詞", category:"場所" },
  { de:"die Party", en:["party"], jp:["パーティー"], pos:"名詞", category:"社会" },
  { de:"die Pause", en:["break"], jp:["休憩"], pos:"名詞", category:"時間" },
  { de:"die Person", en:["person"], jp:["人"], pos:"名詞", category:"人" },
  { de:"das Pferd", en:["horse"], jp:["馬"], pos:"名詞", category:"自然" },
  { de:"die Pizza", en:["pizza"], jp:["ピザ"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Platz", en:["place","square"], jp:["場所","広場"], pos:"名詞", category:"場所" },
  { de:"die Post", en:["post office","mail"], jp:["郵便局","郵便"], pos:"名詞", category:"社会" },
  { de:"der Preis", en:["price","prize"], jp:["値段","賞"], pos:"名詞", category:"社会" },
  { de:"das Problem", en:["problem"], jp:["問題"], pos:"名詞", category:"学習" },
  { de:"der Professor", en:["professor"], jp:["教授"], pos:"名詞", category:"人" },

  { de:"das Radio", en:["radio"], jp:["ラジオ"], pos:"名詞", category:"物" },
  { de:"der Regen", en:["rain"], jp:["雨"], pos:"名詞", category:"自然" },
  { de:"das Restaurant", en:["restaurant"], jp:["レストラン"], pos:"名詞", category:"場所" },
  { de:"das Reis", en:["rice"], jp:["米"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"die Reise", en:["trip","journey"], jp:["旅行"], pos:"名詞", category:"移動" },

  { de:"der Saft", en:["juice"], jp:["ジュース"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Salat", en:["salad"], jp:["サラダ"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"das Salz", en:["salt"], jp:["塩"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Samstag", en:["Saturday"], jp:["土曜日"], pos:"名詞", category:"時間" },
  { de:"die Schule", en:["school"], jp:["学校"], pos:"名詞", category:"学習" },
  { de:"der Schüler", en:["student","pupil"], jp:["男子生徒"], pos:"名詞", category:"人" },
  { de:"die Schülerin", en:["student","pupil"], jp:["女子生徒"], pos:"名詞", category:"人" },
  { de:"das Schwimmbad", en:["swimming pool"], jp:["プール"], pos:"名詞", category:"場所" },
  { de:"die Schwester", en:["sister"], jp:["姉妹"], pos:"名詞", category:"人" },
  { de:"der See", en:["lake"], jp:["湖"], pos:"名詞", category:"自然" },
  { de:"der Sommer", en:["summer"], jp:["夏"], pos:"名詞", category:"時間" },
  { de:"die Sonne", en:["sun"], jp:["太陽"], pos:"名詞", category:"自然" },
  { de:"die Sprache", en:["language"], jp:["言語"], pos:"名詞", category:"学習" },
  { de:"die Stadt", en:["city"], jp:["街"], pos:"名詞", category:"場所" },
  { de:"die Straße", en:["street"], jp:["通り"], pos:"名詞", category:"交通" },
  { de:"der Student", en:["student"], jp:["男子学生"], pos:"名詞", category:"人" },
  { de:"die Studentin", en:["student"], jp:["女子学生"], pos:"名詞", category:"人" },
  { de:"die Stunde", en:["hour","lesson"], jp:["時間","授業"], pos:"名詞", category:"時間" },

  { de:"der Tag", en:["day"], jp:["日"], pos:"名詞", category:"時間" },
  { de:"das Taxi", en:["taxi"], jp:["タクシー"], pos:"名詞", category:"交通" },
  { de:"der Tee", en:["tea"], jp:["お茶"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"der Tisch", en:["table"], jp:["テーブル"], pos:"名詞", category:"家・家具" },
  { de:"die Tochter", en:["daughter"], jp:["娘"], pos:"名詞", category:"人" },
  { de:"die Toilette", en:["toilet"], jp:["トイレ"], pos:"名詞", category:"家・家具" },
  { de:"die Tomate", en:["tomato"], jp:["トマト"], pos:"名詞", category:"食べ物・飲み物" },

  { de:"die Uhr", en:["clock","watch"], jp:["時計"], pos:"名詞", category:"物" },
  { de:"die Universität", en:["university"], jp:["大学"], pos:"名詞", category:"学習" },

  { de:"der Vater", en:["father"], jp:["父"], pos:"名詞", category:"人" },
  { de:"der Vogel", en:["bird"], jp:["鳥"], pos:"名詞", category:"自然" },

  { de:"die Wand", en:["wall"], jp:["壁"], pos:"名詞", category:"家・家具" },
  { de:"das Wasser", en:["water"], jp:["水"], pos:"名詞", category:"食べ物・飲み物" },
  { de:"das Wetter", en:["weather"], jp:["天気"], pos:"名詞", category:"自然" },
  { de:"der Winter", en:["winter"], jp:["冬"], pos:"名詞", category:"時間" },
  { de:"die Wohnung", en:["apartment"], jp:["アパート"], pos:"名詞", category:"家・家具" },
  { de:"das Wort", en:["word"], jp:["単語"], pos:"名詞", category:"学習" },

  { de:"die Zeitung", en:["newspaper"], jp:["新聞"], pos:"名詞", category:"学習" },
  { de:"das Zimmer", en:["room"], jp:["部屋"], pos:"名詞", category:"家・家具" },
  { de:"der Zug", en:["train"], jp:["電車"], pos:"名詞", category:"交通" },
  { de:"die Zukunft", en:["future"], jp:["未来"], pos:"名詞", category:"時間" }
];