const words_de_adverbs = [
  { de:"abends", en:["in the evening"], jp:["夕方に","夜に"], pos:"副詞", category:"時間" },
  { de:"aber", en:["but","however"], jp:["しかし"], pos:"副詞", category:"会話" },
  { de:"allein", en:["alone"], jp:["ひとりで"], pos:"副詞", category:"状態" },
  { de:"allerdings", en:["however","indeed"], jp:["もっとも","ただし"], pos:"副詞", category:"会話" },
  { de:"also", en:["so","therefore"], jp:["だから","つまり"], pos:"副詞", category:"会話" },
  { de:"anderswo", en:["elsewhere"], jp:["ほかの場所で"], pos:"副詞", category:"場所" },
  { de:"außen", en:["outside"], jp:["外に"], pos:"副詞", category:"場所" },
  { de:"außerdem", en:["besides","in addition"], jp:["そのうえ","さらに"], pos:"副詞", category:"会話" },

  { de:"bald", en:["soon"], jp:["すぐに"], pos:"副詞", category:"時間" },
  { de:"beinahe", en:["almost"], jp:["ほとんど"], pos:"副詞", category:"程度" },
  { de:"bereits", en:["already"], jp:["すでに"], pos:"副詞", category:"時間" },
  { de:"besonders", en:["especially"], jp:["特に"], pos:"副詞", category:"程度" },
  { de:"bisher", en:["until now","so far"], jp:["これまで"], pos:"副詞", category:"時間" },
  { de:"bitte", en:["please"], jp:["どうぞ","お願いします"], pos:"副詞", category:"会話" },
  { de:"baldmöglichst", en:["as soon as possible"], jp:["できるだけ早く"], pos:"副詞", category:"時間" },

  { de:"damals", en:["at that time"], jp:["そのころ"], pos:"副詞", category:"時間" },
  { de:"danach", en:["after that"], jp:["そのあとで"], pos:"副詞", category:"時間" },
  { de:"dann", en:["then"], jp:["そのとき","それから"], pos:"副詞", category:"時間" },
  { de:"darum", en:["therefore"], jp:["それゆえに"], pos:"副詞", category:"会話" },
  { de:"davor", en:["before that"], jp:["その前に"], pos:"副詞", category:"時間" },
  { de:"demnächst", en:["soon"], jp:["近いうちに"], pos:"副詞", category:"時間" },
  { de:"deshalb", en:["therefore"], jp:["それだから"], pos:"副詞", category:"会話" },
  { de:"dort", en:["there"], jp:["そこに","あそこに"], pos:"副詞", category:"場所" },
  { de:"dorthin", en:["to there"], jp:["そこへ","あそこへ"], pos:"副詞", category:"場所" },
  { de:"drinnen", en:["inside"], jp:["中で"], pos:"副詞", category:"場所" },
  { de:"drüben", en:["over there"], jp:["向こうに"], pos:"副詞", category:"場所" },

  { de:"eben", en:["just","exactly"], jp:["ちょうど"], pos:"副詞", category:"程度" },
  { de:"ebenfalls", en:["also","likewise"], jp:["同様に"], pos:"副詞", category:"会話" },
  { de:"eigentlich", en:["actually"], jp:["実は","本来は"], pos:"副詞", category:"会話" },
  { de:"einfach", en:["simply"], jp:["単に"], pos:"副詞", category:"程度" },
  { de:"einmal", en:["once"], jp:["一度"], pos:"副詞", category:"時間" },
  { de:"endlich", en:["finally"], jp:["ついに"], pos:"副詞", category:"時間" },
  { de:"etwa", en:["about","approximately"], jp:["およそ"], pos:"副詞", category:"数字" },
  { de:"etwas", en:["a little","somewhat"], jp:["少し"], pos:"副詞", category:"程度" },

  { de:"fast", en:["almost"], jp:["ほとんど"], pos:"副詞", category:"程度" },
  { de:"früher", en:["earlier","formerly"], jp:["以前は","もっと早く"], pos:"副詞", category:"時間" },

  { de:"ganz", en:["quite","completely"], jp:["とても","完全に"], pos:"副詞", category:"程度" },
  { de:"gar", en:["at all","even"], jp:["全然","まったく"], pos:"副詞", category:"強調" },
  { de:"genau", en:["exactly"], jp:["正確に"], pos:"副詞", category:"程度" },
  { de:"gern", en:["gladly"], jp:["喜んで"], pos:"副詞", category:"感情" },
  { de:"gerade", en:["just","right now"], jp:["ちょうど","今まさに"], pos:"副詞", category:"時間" },
  { de:"gestern", en:["yesterday"], jp:["昨日"], pos:"副詞", category:"時間" },
  { de:"gleich", en:["immediately","soon"], jp:["すぐに"], pos:"副詞", category:"時間" },
  { de:"glücklicherweise", en:["fortunately"], jp:["幸いにも"], pos:"副詞", category:"感情" },

  { de:"heim", en:["home"], jp:["家へ"], pos:"副詞", category:"場所" },
  { de:"heute", en:["today"], jp:["今日"], pos:"副詞", category:"時間" },
  { de:"heutzutage", en:["nowadays"], jp:["今日では"], pos:"副詞", category:"時間" },
  { de:"hier", en:["here"], jp:["ここに"], pos:"副詞", category:"場所" },
  { de:"hinaus", en:["out"], jp:["外へ"], pos:"副詞", category:"場所" },

  { de:"immer", en:["always"], jp:["いつも"], pos:"副詞", category:"時間" },
  { de:"innen", en:["inside"], jp:["内側に"], pos:"副詞", category:"場所" },
  { de:"insgesamt", en:["in total","altogether"], jp:["全部で"], pos:"副詞", category:"数字" },
  { de:"inzwischen", en:["meanwhile"], jp:["その間に"], pos:"副詞", category:"時間" },
  { de:"irgendwann", en:["sometime"], jp:["いつか"], pos:"副詞", category:"時間" },
  { de:"irgendwo", en:["somewhere"], jp:["どこかで"], pos:"副詞", category:"場所" },

  { de:"jetzt", en:["now"], jp:["今"], pos:"副詞", category:"時間" },
  { de:"jedoch", en:["however"], jp:["しかし"], pos:"副詞", category:"会話" },

  { de:"kaum", en:["hardly","barely"], jp:["ほとんど〜ない"], pos:"副詞", category:"程度" },
  { de:"kurz", en:["briefly"], jp:["簡潔に"], pos:"副詞", category:"時間" },

  { de:"langsam", en:["slowly"], jp:["ゆっくり"], pos:"副詞", category:"時間" },
  { de:"leider", en:["unfortunately"], jp:["残念ながら"], pos:"副詞", category:"感情" },
  { de:"links", en:["on the left","left"], jp:["左に"], pos:"副詞", category:"場所" },
  { de:"locker", en:["loosely"], jp:["ゆるく"], pos:"副詞", category:"程度" },

  { de:"manchmal", en:["sometimes"], jp:["ときどき"], pos:"副詞", category:"時間" },
  { de:"mehr", en:["more"], jp:["もっと"], pos:"副詞", category:"程度" },
  { de:"meistens", en:["mostly","usually"], jp:["たいてい"], pos:"副詞", category:"時間" },
  { de:"mitten", en:["in the middle"], jp:["真ん中に"], pos:"副詞", category:"場所" },
  { de:"morgen", en:["tomorrow","in the morning"], jp:["明日","朝に"], pos:"副詞", category:"時間" },

  { de:"nachher", en:["afterwards","later"], jp:["あとで"], pos:"副詞", category:"時間" },
  { de:"natürlich", en:["of course","naturally"], jp:["もちろん"], pos:"副詞", category:"会話" },
  { de:"nebenan", en:["next door"], jp:["隣に"], pos:"副詞", category:"場所" },
  { de:"nie", en:["never"], jp:["決して〜ない"], pos:"副詞", category:"時間" },
  { de:"nirgendwo", en:["nowhere"], jp:["どこにも〜ない"], pos:"副詞", category:"場所" },
  { de:"noch", en:["still","yet"], jp:["まだ"], pos:"副詞", category:"時間" },
  { de:"normalerweise", en:["normally"], jp:["普通は"], pos:"副詞", category:"時間" },
  { de:"nun", en:["now","well then"], jp:["さて","今"], pos:"副詞", category:"会話" },
  { de:"nur", en:["only"], jp:["ただ","だけ"], pos:"副詞", category:"程度" },

  { de:"oben", en:["above","upstairs"], jp:["上に"], pos:"副詞", category:"場所" },
  { de:"oft", en:["often"], jp:["しばしば"], pos:"副詞", category:"時間" },

  { de:"plötzlich", en:["suddenly"], jp:["突然"], pos:"副詞", category:"時間" },
  { de:"praktisch", en:["practically"], jp:["実際上"], pos:"副詞", category:"程度" },

  { de:"rechts", en:["on the right","right"], jp:["右に"], pos:"副詞", category:"場所" },
  { de:"regelmäßig", en:["regularly"], jp:["規則的に"], pos:"副詞", category:"時間" },
  { de:"relativ", en:["relatively"], jp:["比較的"], pos:"副詞", category:"程度" },
  { de:"ruhig", en:["calmly","quietly"], jp:["静かに"], pos:"副詞", category:"状態" },

  { de:"schließlich", en:["finally","after all"], jp:["結局"], pos:"副詞", category:"会話" },
  { de:"schon", en:["already"], jp:["もう","すでに"], pos:"副詞", category:"時間" },
  { de:"sehr", en:["very"], jp:["とても"], pos:"副詞", category:"程度" },
  { de:"selbst", en:["even","self"], jp:["自分で","〜さえ"], pos:"副詞", category:"強調" },
  { de:"selten", en:["rarely"], jp:["めったに〜ない"], pos:"副詞", category:"時間" },
  { de:"sicher", en:["surely","certainly"], jp:["確かに"], pos:"副詞", category:"思考" },
  { de:"so", en:["so","thus"], jp:["そんなに","そのように"], pos:"副詞", category:"程度" },
  { de:"sofort", en:["immediately"], jp:["すぐに"], pos:"副詞", category:"時間" },
  { de:"später", en:["later"], jp:["あとで"], pos:"副詞", category:"時間" },
  { de:"stark", en:["strongly"], jp:["強く"], pos:"副詞", category:"程度" },
  { de:"ständig", en:["constantly"], jp:["絶えず"], pos:"副詞", category:"時間" },

  { de:"täglich", en:["daily"], jp:["毎日"], pos:"副詞", category:"時間" },
  { de:"tatsächlich", en:["actually","indeed"], jp:["実際に"], pos:"副詞", category:"会話" },
  { de:"trotzdem", en:["nevertheless"], jp:["それにもかかわらず"], pos:"副詞", category:"会話" },

  { de:"überall", en:["everywhere"], jp:["至る所に"], pos:"副詞", category:"場所" },
  { de:"übrigens", en:["by the way"], jp:["ところで"], pos:"副詞", category:"会話" },
  { de:"unten", en:["below","downstairs"], jp:["下に"], pos:"副詞", category:"場所" },

  { de:"vielleicht", en:["perhaps","maybe"], jp:["たぶん"], pos:"副詞", category:"思考" },
  { de:"vorher", en:["beforehand"], jp:["前に"], pos:"副詞", category:"時間" },

  { de:"wahrscheinlich", en:["probably"], jp:["おそらく"], pos:"副詞", category:"思考" },
  { de:"wenigstens", en:["at least"], jp:["少なくとも"], pos:"副詞", category:"程度" },
  { de:"wieder", en:["again"], jp:["再び"], pos:"副詞", category:"時間" },
  { de:"wirklich", en:["really"], jp:["本当に"], pos:"副詞", category:"強調" },
  { de:"woanders", en:["somewhere else"], jp:["ほかの場所で"], pos:"副詞", category:"場所" },

  { de:"ziemlich", en:["quite","rather"], jp:["かなり"], pos:"副詞", category:"程度" },
  { de:"zuerst", en:["first"], jp:["まず最初に"], pos:"副詞", category:"時間" },
  { de:"zuletzt", en:["lastly","finally"], jp:["最後に"], pos:"副詞", category:"時間" },
  { de:"zufällig", en:["by chance"], jp:["偶然に"], pos:"副詞", category:"状態" },
  { de:"zusammen", en:["together"], jp:["一緒に"], pos:"副詞", category:"状態" }
];