const words_de_verbs = [
  { de:"antworten", en:["answer","reply"], jp:["答える","返事をする"], pos:"動詞", category:"会話" },
  { de:"arbeiten", en:["work"], jp:["働く"], pos:"動詞", category:"行動" },
  { de:"bedeuten", en:["mean"], jp:["意味する"], pos:"動詞", category:"学習" },
  { de:"beginnen", en:["begin","start"], jp:["始める"], pos:"動詞", category:"時間" },
  { de:"bekommen", en:["get","receive"], jp:["受け取る","手に入れる"], pos:"動詞", category:"所有・変化" },
  { de:"benutzen", en:["use"], jp:["使う"], pos:"動詞", category:"行動" },
  { de:"besuchen", en:["visit"], jp:["訪れる"], pos:"動詞", category:"移動" },
  { de:"bezahlen", en:["pay"], jp:["支払う"], pos:"動詞", category:"社会" },
  { de:"bleiben", en:["stay","remain"], jp:["とどまる","残る"], pos:"動詞", category:"状態" },
  { de:"brauchen", en:["need"], jp:["必要とする"], pos:"動詞", category:"状態" },
  { de:"bringen", en:["bring"], jp:["持ってくる"], pos:"動詞", category:"移動" },

  { de:"denken", en:["think"], jp:["考える"], pos:"動詞", category:"思考" },
  { de:"danken", en:["thank"], jp:["感謝する"], pos:"動詞", category:"会話" },
  { de:"dauern", en:["last","take"], jp:["続く","かかる"], pos:"動詞", category:"時間" },

  { de:"empfehlen", en:["recommend"], jp:["勧める"], pos:"動詞", category:"会話" },
  { de:"entscheiden", en:["decide"], jp:["決める"], pos:"動詞", category:"思考" },
  { de:"erfahren", en:["learn","find out"], jp:["知る"], pos:"動詞", category:"学習" },
  { de:"erinnern", en:["remember"], jp:["思い出す"], pos:"動詞", category:"思考" },
  { de:"erklären", en:["explain"], jp:["説明する"], pos:"動詞", category:"会話" },
  { de:"erzählen", en:["tell","narrate"], jp:["話す","語る"], pos:"動詞", category:"会話" },
  { de:"essen", en:["eat"], jp:["食べる"], pos:"動詞", category:"食べ物・飲み物" },

  { de:"fahren", en:["go","drive","ride"], jp:["行く","運転する","乗って行く"], pos:"動詞", category:"移動" },
  { de:"fallen", en:["fall"], jp:["落ちる"], pos:"動詞", category:"変化" },
  { de:"fehlen", en:["be missing","lack"], jp:["欠けている","足りない"], pos:"動詞", category:"状態" },
  { de:"feiern", en:["celebrate"], jp:["祝う"], pos:"動詞", category:"社会" },
  { de:"finden", en:["find"], jp:["見つける"], pos:"動詞", category:"行動" },
  { de:"fliegen", en:["fly"], jp:["飛ぶ"], pos:"動詞", category:"移動" },
  { de:"fragen", en:["ask"], jp:["尋ねる"], pos:"動詞", category:"会話" },
  { de:"fühlen", en:["feel"], jp:["感じる"], pos:"動詞", category:"感情" },

  { de:"geben", en:["give"], jp:["与える"], pos:"動詞", category:"行動" },
  { de:"gefallen", en:["please","appeal to"], jp:["気に入る"], pos:"動詞", category:"感情" },
  { de:"gehören", en:["belong"], jp:["属する"], pos:"動詞", category:"所属" },
  { de:"gelten", en:["be valid","apply"], jp:["当てはまる","有効である"], pos:"動詞", category:"状態" },
  { de:"genießen", en:["enjoy"], jp:["楽しむ"], pos:"動詞", category:"感情" },
  { de:"geschehen", en:["happen"], jp:["起こる"], pos:"動詞", category:"変化" },
  { de:"glauben", en:["believe"], jp:["信じる"], pos:"動詞", category:"思考" },

  { de:"haben", en:["have"], jp:["持っている"], pos:"動詞", category:"所有・変化" },
  { de:"halten", en:["hold","stop"], jp:["持つ","止まる"], pos:"動詞", category:"行動" },
  { de:"heißen", en:["be called","mean"], jp:["〜という名前である","意味する"], pos:"動詞", category:"会話" },
  { de:"helfen", en:["help"], jp:["助ける"], pos:"動詞", category:"行動" },
  { de:"hören", en:["hear","listen"], jp:["聞く"], pos:"動詞", category:"行動" },
  { de:"hoffen", en:["hope"], jp:["望む"], pos:"動詞", category:"感情" },

  { de:"kennen", en:["know","be familiar with"], jp:["知っている"], pos:"動詞", category:"思考" },
  { de:"kommen", en:["come"], jp:["来る"], pos:"動詞", category:"移動" },
  { de:"kosten", en:["cost"], jp:["費用がかかる"], pos:"動詞", category:"社会" },

  { de:"lachen", en:["laugh"], jp:["笑う"], pos:"動詞", category:"感情" },
  { de:"leben", en:["live"], jp:["生きる","暮らす"], pos:"動詞", category:"状態" },
  { de:"legen", en:["lay","put"], jp:["置く"], pos:"動詞", category:"行動" },
  { de:"lernen", en:["learn","study"], jp:["学ぶ"], pos:"動詞", category:"学習" },
  { de:"lesen", en:["read"], jp:["読む"], pos:"動詞", category:"学習" },
  { de:"lieben", en:["love"], jp:["愛する"], pos:"動詞", category:"感情" },
  { de:"liegen", en:["lie"], jp:["横たわる","ある"], pos:"動詞", category:"場所" },

  { de:"machen", en:["do","make"], jp:["する","作る"], pos:"動詞", category:"行動" },
  { de:"meinen", en:["mean","think"], jp:["意味する","思う"], pos:"動詞", category:"思考" },
  { de:"merken", en:["notice","remember"], jp:["気づく","覚える"], pos:"動詞", category:"思考" },
  { de:"mögen", en:["like"], jp:["好む"], pos:"動詞", category:"感情" },
  { de:"müssen", en:["must","have to"], jp:["〜しなければならない"], pos:"動詞", category:"状態" },

  { de:"nehmen", en:["take"], jp:["取る"], pos:"動詞", category:"行動" },
  { de:"nennen", en:["call","name"], jp:["呼ぶ","名付ける"], pos:"動詞", category:"会話" },

  { de:"öffnen", en:["open"], jp:["開ける"], pos:"動詞", category:"行動" },

  { de:"passen", en:["fit","suit"], jp:["合う"], pos:"動詞", category:"状態" },
  { de:"planen", en:["plan"], jp:["計画する"], pos:"動詞", category:"思考" },
  { de:"probieren", en:["try"], jp:["試す"], pos:"動詞", category:"行動" },

  { de:"rauchen", en:["smoke"], jp:["たばこを吸う"], pos:"動詞", category:"体" },
  { de:"reden", en:["talk"], jp:["話す"], pos:"動詞", category:"会話" },
  { de:"regnen", en:["rain"], jp:["雨が降る"], pos:"動詞", category:"自然" },
  { de:"reisen", en:["travel"], jp:["旅行する"], pos:"動詞", category:"移動" },
  { de:"rufen", en:["call","shout"], jp:["呼ぶ","叫ぶ"], pos:"動詞", category:"会話" },

  { de:"sagen", en:["say"], jp:["言う"], pos:"動詞", category:"会話" },
  { de:"schaffen", en:["manage","accomplish"], jp:["成し遂げる"], pos:"動詞", category:"行動" },
  { de:"schauen", en:["look","watch"], jp:["見る"], pos:"動詞", category:"行動" },
  { de:"scheinen", en:["seem","shine"], jp:["〜のように見える","輝く"], pos:"動詞", category:"状態" },
  { de:"schicken", en:["send"], jp:["送る"], pos:"動詞", category:"移動" },
  { de:"schlafen", en:["sleep"], jp:["眠る"], pos:"動詞", category:"体" },
  { de:"schließen", en:["close"], jp:["閉める"], pos:"動詞", category:"行動" },
  { de:"schmecken", en:["taste"], jp:["味がする"], pos:"動詞", category:"食べ物・飲み物" },
  { de:"schneiden", en:["cut"], jp:["切る"], pos:"動詞", category:"行動" },
  { de:"schreiben", en:["write"], jp:["書く"], pos:"動詞", category:"学習" },
  { de:"schwimmen", en:["swim"], jp:["泳ぐ"], pos:"動詞", category:"行動" },
  { de:"sehen", en:["see"], jp:["見る"], pos:"動詞", category:"行動" },
  { de:"sein", en:["be"], jp:["〜である"], pos:"動詞", category:"状態" },
  { de:"singen", en:["sing"], jp:["歌う"], pos:"動詞", category:"芸術" },
  { de:"sitzen", en:["sit"], jp:["座る"], pos:"動詞", category:"体" },
  { de:"spielen", en:["play"], jp:["遊ぶ","演奏する"], pos:"動詞", category:"行動" },
  { de:"sprechen", en:["speak"], jp:["話す"], pos:"動詞", category:"会話" },
  { de:"stehen", en:["stand"], jp:["立つ"], pos:"動詞", category:"体" },
  { de:"stellen", en:["put","place"], jp:["置く"], pos:"動詞", category:"行動" },
  { de:"stimmen", en:["be correct"], jp:["正しい"], pos:"動詞", category:"状態" },
  { de:"studieren", en:["study"], jp:["大学で勉強する"], pos:"動詞", category:"学習" },
  { de:"suchen", en:["search","look for"], jp:["探す"], pos:"動詞", category:"行動" },

  { de:"tanzen", en:["dance"], jp:["踊る"], pos:"動詞", category:"芸術" },
  { de:"teilen", en:["share","divide"], jp:["分ける","共有する"], pos:"動詞", category:"行動" },
  { de:"telefonieren", en:["call","phone"], jp:["電話する"], pos:"動詞", category:"会話" },
  { de:"tragen", en:["carry","wear"], jp:["運ぶ","身につける"], pos:"動詞", category:"行動" },
  { de:"treffen", en:["meet"], jp:["会う"], pos:"動詞", category:"会話" },
  { de:"trinken", en:["drink"], jp:["飲む"], pos:"動詞", category:"食べ物・飲み物" },

  { de:"übernachten", en:["stay overnight"], jp:["泊まる"], pos:"動詞", category:"移動" },
  { de:"übersetzen", en:["translate"], jp:["翻訳する"], pos:"動詞", category:"学習" },

  { de:"verbringen", en:["spend"], jp:["（時間を）過ごす"], pos:"動詞", category:"時間" },
  { de:"vergessen", en:["forget"], jp:["忘れる"], pos:"動詞", category:"思考" },
  { de:"vergleichen", en:["compare"], jp:["比較する"], pos:"動詞", category:"学習" },
  { de:"verstehen", en:["understand"], jp:["理解する"], pos:"動詞", category:"思考" },
  { de:"versuchen", en:["try","attempt"], jp:["試みる"], pos:"動詞", category:"行動" },

  { de:"warten", en:["wait"], jp:["待つ"], pos:"動詞", category:"時間" },
  { de:"wechseln", en:["change","switch"], jp:["変える","乗り換える"], pos:"動詞", category:"変化" },
  { de:"weinen", en:["cry"], jp:["泣く"], pos:"動詞", category:"感情" },
  { de:"werden", en:["become","will"], jp:["〜になる"], pos:"動詞", category:"変化" },
  { de:"wissen", en:["know"], jp:["知っている"], pos:"動詞", category:"思考" },
  { de:"wohnen", en:["live","reside"], jp:["住む"], pos:"動詞", category:"場所" },
  { de:"wollen", en:["want"], jp:["〜したい"], pos:"動詞", category:"感情" },

  { de:"zeigen", en:["show"], jp:["見せる"], pos:"動詞", category:"会話" },
  { de:"zahlen", en:["pay"], jp:["支払う"], pos:"動詞", category:"社会" },
  { de:"zuhören", en:["listen"], jp:["耳を傾ける"], pos:"動詞", category:"会話" }
];