const words_en_verbs = [
  { en:"achieve", jp:["達成する"], pos:"動詞", category:"行動" },
  { en:"acquire", jp:["習得する","得る"], pos:"動詞", category:"所有・変化" },
  { en:"adapt", jp:["適応する"], pos:"動詞", category:"変化" },
  { en:"adjust", jp:["調整する"], pos:"動詞", category:"変化" },
  { en:"admit", jp:["認める"], pos:"動詞", category:"会話" },
  { en:"affect", jp:["影響を与える"], pos:"動詞", category:"変化" },
  { en:"aim", jp:["目指す"], pos:"動詞", category:"感情・思考" },
  { en:"analyze", jp:["分析する"], pos:"動詞", category:"学習" },
  { en:"apply", jp:["適用する","申し込む"], pos:"動詞", category:"行動" },
  { en:"approach", jp:["近づく","取り組む"], pos:"動詞", category:"行動" },
  { en:"argue", jp:["主張する","議論する"], pos:"動詞", category:"会話" },
  { en:"assume", jp:["仮定する"], pos:"動詞", category:"思考" },
  { en:"attempt", jp:["試みる"], pos:"動詞", category:"行動" },
  { en:"avoid", jp:["避ける"], pos:"動詞", category:"行動" },

  { en:"benefit", jp:["利益を得る"], pos:"動詞", category:"社会" },
  { en:"challenge", jp:["挑戦する"], pos:"動詞", category:"行動" },
  { en:"claim", jp:["主張する"], pos:"動詞", category:"会話" },
  { en:"compare", jp:["比較する"], pos:"動詞", category:"学習" },
  { en:"conclude", jp:["結論づける"], pos:"動詞", category:"思考" },
  { en:"conduct", jp:["実施する"], pos:"動詞", category:"行動" },
  { en:"confirm", jp:["確認する"], pos:"動詞", category:"会話" },
  { en:"consider", jp:["考慮する"], pos:"動詞", category:"思考" },
  { en:"consist", jp:["成り立つ"], pos:"動詞", category:"状態" },
  { en:"contribute", jp:["貢献する"], pos:"動詞", category:"社会" },
  { en:"control", jp:["制御する"], pos:"動詞", category:"行動" },
  { en:"convince", jp:["納得させる"], pos:"動詞", category:"会話" },
  { en:"create", jp:["創造する"], pos:"動詞", category:"行動" },

  { en:"decline", jp:["減少する","断る"], pos:"動詞", category:"変化" },
  { en:"define", jp:["定義する"], pos:"動詞", category:"学習" },
  { en:"demonstrate", jp:["示す","実証する"], pos:"動詞", category:"会話" },
  { en:"derive", jp:["引き出す"], pos:"動詞", category:"思考" },
  { en:"determine", jp:["決定する"], pos:"動詞", category:"思考" },
  { en:"develop", jp:["発展させる"], pos:"動詞", category:"変化" },
  { en:"distinguish", jp:["区別する"], pos:"動詞", category:"学習" },

  { en:"emphasize", jp:["強調する"], pos:"動詞", category:"会話" },
  { en:"enable", jp:["可能にする"], pos:"動詞", category:"変化" },
  { en:"encourage", jp:["促す"], pos:"動詞", category:"感情" },
  { en:"engage", jp:["従事する"], pos:"動詞", category:"行動" },
  { en:"enhance", jp:["高める"], pos:"動詞", category:"変化" },
  { en:"ensure", jp:["確実にする"], pos:"動詞", category:"行動" },
  { en:"establish", jp:["確立する"], pos:"動詞", category:"社会" },
  { en:"evaluate", jp:["評価する"], pos:"動詞", category:"学習" },
  { en:"examine", jp:["調査する"], pos:"動詞", category:"学習" },
  { en:"expand", jp:["拡大する"], pos:"動詞", category:"変化" },
  { en:"explore", jp:["探求する"], pos:"動詞", category:"学習" },
  { en:"express", jp:["表現する"], pos:"動詞", category:"会話" },

  { en:"focus", jp:["集中する"], pos:"動詞", category:"思考" },
  { en:"function", jp:["機能する"], pos:"動詞", category:"状態" },

  { en:"generate", jp:["生み出す"], pos:"動詞", category:"変化" },
  { en:"identify", jp:["特定する"], pos:"動詞", category:"学習" },
  { en:"ignore", jp:["無視する"], pos:"動詞", category:"行動" },
  { en:"illustrate", jp:["説明する"], pos:"動詞", category:"会話" },
  { en:"imply", jp:["暗に示す"], pos:"動詞", category:"会話" },
  { en:"improve", jp:["改善する"], pos:"動詞", category:"変化" },
  { en:"include", jp:["含む"], pos:"動詞", category:"状態" },
  { en:"indicate", jp:["示す"], pos:"動詞", category:"会話" },
  { en:"influence", jp:["影響を与える"], pos:"動詞", category:"変化" },
  { en:"interpret", jp:["解釈する"], pos:"動詞", category:"思考" },
  { en:"introduce", jp:["導入する","紹介する"], pos:"動詞", category:"会話" },
  { en:"involve", jp:["含む","関与する"], pos:"動詞", category:"状態" },

  { en:"maintain", jp:["維持する"], pos:"動詞", category:"状態" },
  { en:"manage", jp:["管理する"], pos:"動詞", category:"行動" },
  { en:"measure", jp:["測定する"], pos:"動詞", category:"学習" },
  { en:"mention", jp:["言及する"], pos:"動詞", category:"会話" },

  { en:"observe", jp:["観察する"], pos:"動詞", category:"学習" },
  { en:"obtain", jp:["得る"], pos:"動詞", category:"所有・変化" },
  { en:"occur", jp:["起こる"], pos:"動詞", category:"変化" },
  { en:"offer", jp:["提供する"], pos:"動詞", category:"行動" },

  { en:"perform", jp:["実行する"], pos:"動詞", category:"行動" },
  { en:"permit", jp:["許可する"], pos:"動詞", category:"行動" },
  { en:"predict", jp:["予測する"], pos:"動詞", category:"思考" },
  { en:"prefer", jp:["好む"], pos:"動詞", category:"感情" },
  { en:"prepare", jp:["準備する"], pos:"動詞", category:"行動" },
  { en:"present", jp:["提示する"], pos:"動詞", category:"会話" },
  { en:"prevent", jp:["防ぐ"], pos:"動詞", category:"行動" },
  { en:"promote", jp:["促進する"], pos:"動詞", category:"社会" },
  { en:"propose", jp:["提案する"], pos:"動詞", category:"会話" },
  { en:"prove", jp:["証明する"], pos:"動詞", category:"学習" },
  { en:"provide", jp:["提供する"], pos:"動詞", category:"行動" },

  { en:"recognize", jp:["認識する"], pos:"動詞", category:"思考" },
  { en:"reduce", jp:["減らす"], pos:"動詞", category:"変化" },
  { en:"refer", jp:["言及する"], pos:"動詞", category:"会話" },
  { en:"reflect", jp:["反映する"], pos:"動詞", category:"変化" },
  { en:"reject", jp:["拒否する"], pos:"動詞", category:"行動" },
  { en:"relate", jp:["関連する"], pos:"動詞", category:"状態" },
  { en:"remain", jp:["残る"], pos:"動詞", category:"状態" },
  { en:"remove", jp:["取り除く"], pos:"動詞", category:"行動" },
  { en:"replace", jp:["置き換える"], pos:"動詞", category:"変化" },
  { en:"represent", jp:["表す"], pos:"動詞", category:"会話" },
  { en:"require", jp:["必要とする"], pos:"動詞", category:"状態" },
  { en:"respond", jp:["応答する"], pos:"動詞", category:"会話" },
  { en:"result", jp:["結果として起こる"], pos:"動詞", category:"変化" },
  { en:"reveal", jp:["明らかにする"], pos:"動詞", category:"会話" },

  { en:"select", jp:["選ぶ"], pos:"動詞", category:"行動" },
  { en:"seem", jp:["〜のように見える"], pos:"動詞", category:"状態" },
  { en:"solve", jp:["解決する"], pos:"動詞", category:"学習" },
  { en:"suggest", jp:["提案する"], pos:"動詞", category:"会話" },
  { en:"support", jp:["支持する"], pos:"動詞", category:"社会" },

  { en:"tend", jp:["〜する傾向がある"], pos:"動詞", category:"状態" },
  { en:"treat", jp:["扱う"], pos:"動詞", category:"行動" },

  { en:"underestimate", jp:["過小評価する"], pos:"動詞", category:"思考" },
  { en:"understand", jp:["理解する"], pos:"動詞", category:"思考" },
  { en:"use", jp:["利用する"], pos:"動詞", category:"行動" },

  { en:"vary", jp:["変化する"], pos:"動詞", category:"変化" },

  { en:"warn", jp:["警告する"], pos:"動詞", category:"会話" },
  { en:"witness", jp:["目撃する"], pos:"動詞", category:"行動" }
  ,
  { en:"abandon", jp:["捨てる","断念する"], pos:"動詞", category:"行動" },
  { en:"absorb", jp:["吸収する"], pos:"動詞", category:"変化" },
  { en:"accompany", jp:["伴う","付き添う"], pos:"動詞", category:"移動" },
  { en:"accuse", jp:["非難する","告発する"], pos:"動詞", category:"会話" },
  { en:"acknowledge", jp:["認める"], pos:"動詞", category:"会話" },
  { en:"adopt", jp:["採用する","養子にする"], pos:"動詞", category:"社会" },
  { en:"advocate", jp:["主張する"], pos:"動詞", category:"会話" },
  { en:"allocate", jp:["割り当てる"], pos:"動詞", category:"行動" },
  { en:"alter", jp:["変える"], pos:"動詞", category:"変化" },
  { en:"anticipate", jp:["予期する"], pos:"動詞", category:"思考" },
  { en:"appreciate", jp:["正しく理解する","感謝する"], pos:"動詞", category:"感情" },
  { en:"arise", jp:["生じる"], pos:"動詞", category:"変化" },
  { en:"attach", jp:["取り付ける"], pos:"動詞", category:"行動" },
  { en:"attain", jp:["達成する"], pos:"動詞", category:"行動" },

  { en:"capture", jp:["捕らえる","捉える"], pos:"動詞", category:"行動" },
  { en:"cite", jp:["引用する"], pos:"動詞", category:"学習" },
  { en:"collapse", jp:["崩壊する"], pos:"動詞", category:"変化" },
  { en:"combine", jp:["結びつける"], pos:"動詞", category:"変化" },
  { en:"compensate", jp:["補償する"], pos:"動詞", category:"社会" },
  { en:"comply", jp:["従う"], pos:"動詞", category:"社会" },
  { en:"compose", jp:["構成する","作曲する"], pos:"動詞", category:"芸術" },
  { en:"comprise", jp:["成る","構成する"], pos:"動詞", category:"状態" },
  { en:"conceal", jp:["隠す"], pos:"動詞", category:"行動" },
  { en:"concentrate", jp:["集中する"], pos:"動詞", category:"思考" },
  { en:"confine", jp:["制限する"], pos:"動詞", category:"社会" },
  { en:"confront", jp:["直面する"], pos:"動詞", category:"行動" },
  { en:"conserve", jp:["保存する"], pos:"動詞", category:"自然" },
  { en:"constitute", jp:["構成する"], pos:"動詞", category:"状態" },
  { en:"consume", jp:["消費する"], pos:"動詞", category:"社会" },
  { en:"convey", jp:["伝える"], pos:"動詞", category:"会話" },
  { en:"correspond", jp:["一致する"], pos:"動詞", category:"状態" },
  { en:"cultivate", jp:["育む","耕す"], pos:"動詞", category:"変化" },

  { en:"decrease", jp:["減少する","減らす"], pos:"動詞", category:"変化" },
  { en:"deduce", jp:["推論する"], pos:"動詞", category:"思考" },
  { en:"defend", jp:["守る"], pos:"動詞", category:"行動" },
  { en:"delay", jp:["遅らせる"], pos:"動詞", category:"時間" },
  { en:"deny", jp:["否定する"], pos:"動詞", category:"会話" },
  { en:"depict", jp:["描写する"], pos:"動詞", category:"芸術" },
  { en:"deposit", jp:["預ける"], pos:"動詞", category:"社会" },
  { en:"derive", jp:["引き出す"], pos:"動詞", category:"思考" },
  { en:"descend", jp:["降りる"], pos:"動詞", category:"移動" },
  { en:"deserve", jp:["値する"], pos:"動詞", category:"思考" },
  { en:"detect", jp:["見つける"], pos:"動詞", category:"学習" },
  { en:"diminish", jp:["減少する"], pos:"動詞", category:"変化" },
  { en:"discard", jp:["捨てる"], pos:"動詞", category:"行動" },
  { en:"discriminate", jp:["差別する","区別する"], pos:"動詞", category:"社会" },
  { en:"disrupt", jp:["混乱させる"], pos:"動詞", category:"変化" },

  { en:"eliminate", jp:["除去する"], pos:"動詞", category:"行動" },
  { en:"emerge", jp:["現れる"], pos:"動詞", category:"変化" },
  { en:"encounter", jp:["遭遇する"], pos:"動詞", category:"行動" },
  { en:"endure", jp:["耐える"], pos:"動詞", category:"感情" },
  { en:"enforce", jp:["施行する","強制する"], pos:"動詞", category:"社会" },
  { en:"enroll", jp:["登録する"], pos:"動詞", category:"社会" },
  { en:"equip", jp:["備え付ける"], pos:"動詞", category:"行動" },
  { en:"establish", jp:["設立する","確立する"], pos:"動詞", category:"社会" },
  { en:"estimate", jp:["見積もる"], pos:"動詞", category:"学習" },
  { en:"evolve", jp:["進化する","発展する"], pos:"動詞", category:"変化" },
  { en:"exceed", jp:["超える"], pos:"動詞", category:"数字" },
  { en:"exclude", jp:["除外する"], pos:"動詞", category:"行動" },
  { en:"exhibit", jp:["示す","展示する"], pos:"動詞", category:"会話" },
  { en:"expose", jp:["さらす","暴露する"], pos:"動詞", category:"変化" },
  { en:"extend", jp:["延ばす","広げる"], pos:"動詞", category:"変化" },

  { en:"facilitate", jp:["促進する"], pos:"動詞", category:"社会" },
  { en:"formulate", jp:["まとめる","公式化する"], pos:"動詞", category:"思考" },
  { en:"foster", jp:["育成する"], pos:"動詞", category:"変化" },

  { en:"govern", jp:["統治する"], pos:"動詞", category:"社会" },
  { en:"grant", jp:["与える","認める"], pos:"動詞", category:"社会" },

  { en:"hinder", jp:["妨げる"], pos:"動詞", category:"行動" },

  { en:"impose", jp:["課す","押しつける"], pos:"動詞", category:"社会" },
  { en:"incorporate", jp:["組み込む"], pos:"動詞", category:"変化" },
  { en:"induce", jp:["引き起こす"], pos:"動詞", category:"変化" },
  { en:"infer", jp:["推論する"], pos:"動詞", category:"思考" },
  { en:"inherit", jp:["受け継ぐ"], pos:"動詞", category:"所有・変化" },
  { en:"insist", jp:["強く主張する"], pos:"動詞", category:"会話" },
  { en:"inspire", jp:["鼓舞する"], pos:"動詞", category:"感情" },
  { en:"install", jp:["設置する"], pos:"動詞", category:"行動" },
  { en:"instruct", jp:["指示する","教える"], pos:"動詞", category:"会話" },
  { en:"integrate", jp:["統合する"], pos:"動詞", category:"変化" },
  { en:"invest", jp:["投資する"], pos:"動詞", category:"社会" },

  { en:"justify", jp:["正当化する"], pos:"動詞", category:"思考" },

  { en:"launch", jp:["開始する","発売する"], pos:"動詞", category:"行動" },
  { en:"locate", jp:["位置づける","見つける"], pos:"動詞", category:"場所" },

  { en:"modify", jp:["修正する"], pos:"動詞", category:"変化" },
  { en:"monitor", jp:["監視する"], pos:"動詞", category:"学習" },
  { en:"motivate", jp:["動機づける"], pos:"動詞", category:"感情" },

  { en:"neglect", jp:["怠る"], pos:"動詞", category:"行動" },
  { en:"notify", jp:["知らせる"], pos:"動詞", category:"会話" },

  { en:"overcome", jp:["克服する"], pos:"動詞", category:"行動" },

  { en:"participate", jp:["参加する"], pos:"動詞", category:"社会" },
  { en:"perceive", jp:["知覚する"], pos:"動詞", category:"思考" },
  { en:"persuade", jp:["説得する"], pos:"動詞", category:"会話" },
  { en:"pose", jp:["引き起こす"], pos:"動詞", category:"変化" },
  { en:"preserve", jp:["保護する","保存する"], pos:"動詞", category:"自然" },
  { en:"prohibit", jp:["禁止する"], pos:"動詞", category:"社会" },
  { en:"pursue", jp:["追求する"], pos:"動詞", category:"行動" },

  { en:"quote", jp:["引用する"], pos:"動詞", category:"学習" },

  { en:"react", jp:["反応する"], pos:"動詞", category:"変化" },
  { en:"recover", jp:["回復する"], pos:"動詞", category:"変化" },
  { en:"regard", jp:["見なす"], pos:"動詞", category:"思考" },
  { en:"regulate", jp:["規制する"], pos:"動詞", category:"社会" },
  { en:"reinforce", jp:["強化する"], pos:"動詞", category:"変化" },
  { en:"relieve", jp:["和らげる"], pos:"動詞", category:"感情" },
  { en:"rely", jp:["頼る"], pos:"動詞", category:"状態" },
  { en:"reserve", jp:["予約する","取っておく"], pos:"動詞", category:"行動" },
  { en:"resolve", jp:["解決する"], pos:"動詞", category:"学習" },
  { en:"retain", jp:["保持する"], pos:"動詞", category:"所有・変化" },
  { en:"reverse", jp:["逆転する"], pos:"動詞", category:"変化" },

  { en:"simulate", jp:["模擬実験する","まねる"], pos:"動詞", category:"学習" },
  { en:"specialize", jp:["専門とする"], pos:"動詞", category:"学習" },
  { en:"specify", jp:["明示する"], pos:"動詞", category:"会話" },
  { en:"stimulate", jp:["刺激する"], pos:"動詞", category:"変化" },
  { en:"struggle", jp:["もがく","努力する"], pos:"動詞", category:"行動" },
  { en:"submit", jp:["提出する"], pos:"動詞", category:"行動" },
  { en:"substitute", jp:["代用する"], pos:"動詞", category:"変化" },
  { en:"sustain", jp:["維持する"], pos:"動詞", category:"状態" },

  { en:"transform", jp:["変える"], pos:"動詞", category:"変化" },
  { en:"transmit", jp:["伝える","送る"], pos:"動詞", category:"会話" },

  { en:"undergo", jp:["経験する","受ける"], pos:"動詞", category:"変化" },
  { en:"undertake", jp:["引き受ける"], pos:"動詞", category:"行動" },
  { en:"unify", jp:["統一する"], pos:"動詞", category:"変化" },
  { en:"urge", jp:["強く促す"], pos:"動詞", category:"会話" },

  { en:"violate", jp:["違反する"], pos:"動詞", category:"社会" },

  { en:"withdraw", jp:["引っ込める","撤回する"], pos:"動詞", category:"行動" },
  { en:"withstand", jp:["耐える"], pos:"動詞", category:"状態" }
];