const words_de_others = [
  { de:"aber", en:["but"], jp:["しかし"], pos:"その他", category:"接続" },
  { de:"als", en:["as","than","when"], jp:["〜として","〜より","〜したとき"], pos:"その他", category:"接続" },
  { de:"also", en:["so","therefore"], jp:["だから","それで"], pos:"その他", category:"接続" },
  { de:"an", en:["at","on"], jp:["〜に","〜で"], pos:"その他", category:"前置詞" },
  { de:"auch", en:["also","too"], jp:["〜も"], pos:"その他", category:"接続" },
  { de:"auf", en:["on","onto"], jp:["〜の上に","〜へ"], pos:"その他", category:"前置詞" },
  { de:"aus", en:["out of","from"], jp:["〜から外へ","〜から"], pos:"その他", category:"前置詞" },
  { de:"bei", en:["at","near","with"], jp:["〜で","〜の近くで"], pos:"その他", category:"前置詞" },
  { de:"bis", en:["until","to"], jp:["〜まで"], pos:"その他", category:"前置詞" },
  { de:"dann", en:["then"], jp:["そのとき","それから"], pos:"その他", category:"接続" },
  { de:"dass", en:["that"], jp:["〜ということ"], pos:"その他", category:"接続" },
  { de:"dein", en:["your"], jp:["君の","あなたの"], pos:"その他", category:"代名詞" },
  { de:"denn", en:["because","for"], jp:["なぜなら"], pos:"その他", category:"接続" },
  { de:"der", en:["the"], jp:["その"], pos:"その他", category:"冠詞" },
  { de:"deshalb", en:["therefore"], jp:["それだから"], pos:"その他", category:"接続" },
  { de:"die", en:["the"], jp:["その"], pos:"その他", category:"冠詞" },
  { de:"dies", en:["this"], jp:["この"], pos:"その他", category:"代名詞" },
  { de:"doch", en:["however","after all"], jp:["しかし","やはり"], pos:"その他", category:"接続" },
  { de:"dort", en:["there"], jp:["そこ","あそこ"], pos:"その他", category:"代名詞" },
  { de:"durch", en:["through"], jp:["〜を通って"], pos:"その他", category:"前置詞" },
  { de:"ein", en:["a","an"], jp:["ひとつの"], pos:"その他", category:"冠詞" },
  { de:"eine", en:["a","an"], jp:["ひとつの"], pos:"その他", category:"冠詞" },
  { de:"einige", en:["some","several"], jp:["いくつかの"], pos:"その他", category:"代名詞" },
  { de:"entlang", en:["along"], jp:["〜に沿って"], pos:"その他", category:"前置詞" },
  { de:"er", en:["he"], jp:["彼"], pos:"その他", category:"代名詞" },
  { de:"es", en:["it"], jp:["それ"], pos:"その他", category:"代名詞" },
  { de:"etwas", en:["something","a little"], jp:["何か","少し"], pos:"その他", category:"代名詞" },
  { de:"euer", en:["your (plural)"], jp:["君たちの"], pos:"その他", category:"代名詞" },
  { de:"für", en:["for"], jp:["〜のために"], pos:"その他", category:"前置詞" },
  { de:"gegen", en:["against"], jp:["〜に対して"], pos:"その他", category:"前置詞" },
  { de:"genug", en:["enough"], jp:["十分に"], pos:"その他", category:"代名詞" },
  { de:"hinter", en:["behind"], jp:["〜の後ろに"], pos:"その他", category:"前置詞" },
  { de:"hier", en:["here"], jp:["ここ"], pos:"その他", category:"代名詞" },
  { de:"ich", en:["I"], jp:["私"], pos:"その他", category:"代名詞" },
  { de:"ihr", en:["you (plural)","her","their"], jp:["あなたたち","彼女の","彼らの"], pos:"その他", category:"代名詞" },
  { de:"im", en:["in the"], jp:["〜の中に"], pos:"その他", category:"前置詞" },
  { de:"in", en:["in","into"], jp:["〜の中に"], pos:"その他", category:"前置詞" },
  { de:"indem", en:["by doing"], jp:["〜することによって"], pos:"その他", category:"接続" },
  { de:"ins", en:["into the"], jp:["〜の中へ"], pos:"その他", category:"前置詞" },
  { de:"jeder", en:["every","each"], jp:["すべての"], pos:"その他", category:"代名詞" },
  { de:"kein", en:["no","not any"], jp:["ひとつも〜ない"], pos:"その他", category:"代名詞" },
  { de:"man", en:["one","people"], jp:["人は","誰でも"], pos:"その他", category:"代名詞" },
  { de:"mein", en:["my"], jp:["私の"], pos:"その他", category:"代名詞" },
  { de:"mit", en:["with"], jp:["〜と一緒に"], pos:"その他", category:"前置詞" },
  { de:"nach", en:["after","to"], jp:["〜のあとに","〜へ"], pos:"その他", category:"前置詞" },
  { de:"neben", en:["next to"], jp:["〜のとなりに"], pos:"その他", category:"前置詞" },
  { de:"nicht", en:["not"], jp:["〜でない"], pos:"その他", category:"否定" },
  { de:"nichts", en:["nothing"], jp:["何も〜ない"], pos:"その他", category:"代名詞" },
  { de:"noch", en:["still","yet"], jp:["まだ"], pos:"その他", category:"接続" },
  { de:"nur", en:["only"], jp:["ただ","だけ"], pos:"その他", category:"接続" },
  { de:"ob", en:["whether"], jp:["〜かどうか"], pos:"その他", category:"接続" },
  { de:"oder", en:["or"], jp:["または"], pos:"その他", category:"接続" },
  { de:"ohne", en:["without"], jp:["〜なしで"], pos:"その他", category:"前置詞" },
  { de:"sehr", en:["very"], jp:["とても"], pos:"その他", category:"強調" },
  { de:"sein", en:["his","its"], jp:["彼の","それの"], pos:"その他", category:"代名詞" },
  { de:"seit", en:["since","for"], jp:["〜以来"], pos:"その他", category:"前置詞" },
  { de:"sie", en:["she","they","you (formal)"], jp:["彼女","彼ら","あなた"], pos:"その他", category:"代名詞" },
  { de:"so", en:["so"], jp:["そのように","そんなに"], pos:"その他", category:"接続" },
  { de:"über", en:["over","about"], jp:["〜の上に","〜について"], pos:"その他", category:"前置詞" },
  { de:"um", en:["around","at","in order to"], jp:["〜のまわりに","〜時に","〜するために"], pos:"その他", category:"前置詞" },
  { de:"und", en:["and"], jp:["そして"], pos:"その他", category:"接続" },
  { de:"unter", en:["under"], jp:["〜の下に"], pos:"その他", category:"前置詞" },
  { de:"unser", en:["our"], jp:["私たちの"], pos:"その他", category:"代名詞" },
  { de:"von", en:["from","of"], jp:["〜から","〜の"], pos:"その他", category:"前置詞" },
  { de:"vor", en:["before","in front of"], jp:["〜の前に"], pos:"その他", category:"前置詞" },
  { de:"wann", en:["when"], jp:["いつ"], pos:"その他", category:"疑問詞" },
  { de:"warum", en:["why"], jp:["なぜ"], pos:"その他", category:"疑問詞" },
  { de:"was", en:["what"], jp:["何"], pos:"その他", category:"疑問詞" },
  { de:"wegen", en:["because of"], jp:["〜のために"], pos:"その他", category:"前置詞" },
  { de:"weil", en:["because"], jp:["なぜなら"], pos:"その他", category:"接続" },
  { de:"welch", en:["which","what"], jp:["どの"], pos:"その他", category:"疑問詞" },
  { de:"wenn", en:["if","when"], jp:["もし〜なら","〜するとき"], pos:"その他", category:"接続" },
  { de:"wer", en:["who"], jp:["誰"], pos:"その他", category:"疑問詞" },
  { de:"wie", en:["how"], jp:["どのように"], pos:"その他", category:"疑問詞" },
  { de:"wir", en:["we"], jp:["私たち"], pos:"その他", category:"代名詞" },
  { de:"wo", en:["where"], jp:["どこ"], pos:"その他", category:"疑問詞" },
  { de:"woher", en:["from where"], jp:["どこから"], pos:"その他", category:"疑問詞" },
  { de:"wohin", en:["to where"], jp:["どこへ"], pos:"その他", category:"疑問詞" },
  { de:"zwischen", en:["between"], jp:["〜の間に"], pos:"その他", category:"前置詞" },
  { de:"zu", en:["to","too"], jp:["〜へ","あまりに"], pos:"その他", category:"前置詞" },
  { de:"zum", en:["to the"], jp:["〜へ"], pos:"その他", category:"前置詞" },
  { de:"zur", en:["to the"], jp:["〜へ"], pos:"その他", category:"前置詞" }
];