const words_en_adjectives = [
  { en:"able", jp:["〜できる"], pos:"形容詞", category:"状態" },
  { en:"academic", jp:["学問の","学術的な"], pos:"形容詞", category:"学習" },
  { en:"accurate", jp:["正確な"], pos:"形容詞", category:"学習" },
  { en:"active", jp:["活動的な"], pos:"形容詞", category:"行動" },
  { en:"additional", jp:["追加の"], pos:"形容詞", category:"抽象" },
  { en:"adequate", jp:["十分な"], pos:"形容詞", category:"抽象" },
  { en:"advanced", jp:["高度な"], pos:"形容詞", category:"学習" },
  { en:"afraid", jp:["恐れて"], pos:"形容詞", category:"感情" },
  { en:"aggressive", jp:["攻撃的な"], pos:"形容詞", category:"感情" },
  { en:"alive", jp:["生きている"], pos:"形容詞", category:"体" },
  { en:"alternative", jp:["代わりの"], pos:"形容詞", category:"抽象" },
  { en:"amazing", jp:["驚くべき"], pos:"形容詞", category:"感情" },
  { en:"ancient", jp:["古代の"], pos:"形容詞", category:"時間" },
  { en:"anxious", jp:["不安な"], pos:"形容詞", category:"感情" },
  { en:"apparent", jp:["明らかな"], pos:"形容詞", category:"思考" },
  { en:"appropriate", jp:["適切な"], pos:"形容詞", category:"抽象" },
  { en:"artificial", jp:["人工の"], pos:"形容詞", category:"社会" },
  { en:"attractive", jp:["魅力的な"], pos:"形容詞", category:"感情" },
  { en:"available", jp:["利用できる","手に入る"], pos:"形容詞", category:"状態" },
  { en:"aware", jp:["気づいている"], pos:"形容詞", category:"思考" },

  { en:"basic", jp:["基本的な"], pos:"形容詞", category:"学習" },
  { en:"beneficial", jp:["有益な"], pos:"形容詞", category:"抽象" },
  { en:"brief", jp:["短い"], pos:"形容詞", category:"時間" },

  { en:"capable", jp:["能力がある"], pos:"形容詞", category:"状態" },
  { en:"careful", jp:["注意深い"], pos:"形容詞", category:"感情" },
  { en:"certain", jp:["確かな","ある"], pos:"形容詞", category:"思考" },
  { en:"chemical", jp:["化学の"], pos:"形容詞", category:"学習" },
  { en:"civil", jp:["市民の"], pos:"形容詞", category:"社会" },
  { en:"classic", jp:["古典的な"], pos:"形容詞", category:"芸術" },
  { en:"clear", jp:["明らかな"], pos:"形容詞", category:"思考" },
  { en:"clinical", jp:["臨床の"], pos:"形容詞", category:"学習" },
  { en:"common", jp:["一般的な"], pos:"形容詞", category:"抽象" },
  { en:"complex", jp:["複雑な"], pos:"形容詞", category:"抽象" },
  { en:"confident", jp:["自信のある"], pos:"形容詞", category:"感情" },
  { en:"conscious", jp:["意識している"], pos:"形容詞", category:"思考" },
  { en:"constant", jp:["絶え間ない"], pos:"形容詞", category:"時間" },
  { en:"convenient", jp:["便利な"], pos:"形容詞", category:"抽象" },
  { en:"creative", jp:["創造的な"], pos:"形容詞", category:"芸術" },
  { en:"critical", jp:["重大な","批判的な"], pos:"形容詞", category:"思考" },
  { en:"cultural", jp:["文化的な"], pos:"形容詞", category:"社会" },
  { en:"curious", jp:["好奇心が強い"], pos:"形容詞", category:"感情" },

  { en:"daily", jp:["毎日の"], pos:"形容詞", category:"時間" },
  { en:"dangerous", jp:["危険な"], pos:"形容詞", category:"状態" },
  { en:"dead", jp:["死んでいる"], pos:"形容詞", category:"体" },
  { en:"definite", jp:["明確な"], pos:"形容詞", category:"思考" },
  { en:"delicate", jp:["繊細な"], pos:"形容詞", category:"抽象" },
  { en:"dense", jp:["密集した"], pos:"形容詞", category:"抽象" },
  { en:"dependent", jp:["依存している"], pos:"形容詞", category:"状態" },
  { en:"detailed", jp:["詳細な"], pos:"形容詞", category:"学習" },
  { en:"direct", jp:["直接の"], pos:"形容詞", category:"抽象" },
  { en:"distant", jp:["遠い"], pos:"形容詞", category:"場所" },
  { en:"domestic", jp:["国内の","家庭の"], pos:"形容詞", category:"社会" },

  { en:"eager", jp:["熱望している"], pos:"形容詞", category:"感情" },
  { en:"economic", jp:["経済の"], pos:"形容詞", category:"社会" },
  { en:"effective", jp:["効果的な"], pos:"形容詞", category:"抽象" },
  { en:"efficient", jp:["効率的な"], pos:"形容詞", category:"抽象" },
  { en:"elderly", jp:["高齢の"], pos:"形容詞", category:"人" },
  { en:"electrical", jp:["電気の"], pos:"形容詞", category:"学習" },
  { en:"emotional", jp:["感情的な"], pos:"形容詞", category:"感情" },
  { en:"entire", jp:["全体の"], pos:"形容詞", category:"抽象" },
  { en:"environmental", jp:["環境の"], pos:"形容詞", category:"自然" },
  { en:"equal", jp:["等しい"], pos:"形容詞", category:"数字" },
  { en:"essential", jp:["不可欠な"], pos:"形容詞", category:"抽象" },
  { en:"ethical", jp:["倫理的な"], pos:"形容詞", category:"社会" },
  { en:"evident", jp:["明らかな"], pos:"形容詞", category:"思考" },
  { en:"exact", jp:["正確な"], pos:"形容詞", category:"学習" },
  { en:"excellent", jp:["優れた"], pos:"形容詞", category:"抽象" },
  { en:"exhausted", jp:["疲れ果てた"], pos:"形容詞", category:"体" },
  { en:"extensive", jp:["広範囲の"], pos:"形容詞", category:"抽象" },
  { en:"external", jp:["外部の"], pos:"形容詞", category:"場所" },

  { en:"familiar", jp:["よく知られた"], pos:"形容詞", category:"思考" },
  { en:"famous", jp:["有名な"], pos:"形容詞", category:"社会" },
  { en:"federal", jp:["連邦の"], pos:"形容詞", category:"社会" },
  { en:"final", jp:["最終の"], pos:"形容詞", category:"時間" },
  { en:"financial", jp:["財政の"], pos:"形容詞", category:"社会" },
  { en:"flexible", jp:["柔軟な"], pos:"形容詞", category:"抽象" },
  { en:"formal", jp:["正式な"], pos:"形容詞", category:"社会" },
  { en:"frequent", jp:["頻繁な"], pos:"形容詞", category:"時間" },
  { en:"fundamental", jp:["基本的な"], pos:"形容詞", category:"抽象" },

  { en:"general", jp:["一般的な"], pos:"形容詞", category:"抽象" },
  { en:"generous", jp:["寛大な"], pos:"形容詞", category:"感情" },
  { en:"global", jp:["地球規模の"], pos:"形容詞", category:"社会" },
  { en:"gradual", jp:["徐々の"], pos:"形容詞", category:"時間" },
  { en:"grateful", jp:["感謝している"], pos:"形容詞", category:"感情" },

  { en:"harmful", jp:["有害な"], pos:"形容詞", category:"状態" },
  { en:"historical", jp:["歴史上の"], pos:"形容詞", category:"時間" },
  { en:"honest", jp:["正直な"], pos:"形容詞", category:"感情" },
  { en:"huge", jp:["巨大な"], pos:"形容詞", category:"数字" },

  { en:"ideal", jp:["理想的な"], pos:"形容詞", category:"抽象" },
  { en:"immediate", jp:["即座の"], pos:"形容詞", category:"時間" },
  { en:"impressive", jp:["印象的な"], pos:"形容詞", category:"感情" },
  { en:"independent", jp:["独立した"], pos:"形容詞", category:"社会" },
  { en:"individual", jp:["個々の"], pos:"形容詞", category:"抽象" },
  { en:"inevitable", jp:["避けられない"], pos:"形容詞", category:"状態" },
  { en:"informal", jp:["くだけた"], pos:"形容詞", category:"社会" },
  { en:"initial", jp:["最初の"], pos:"形容詞", category:"時間" },
  { en:"inner", jp:["内側の"], pos:"形容詞", category:"場所" },
  { en:"innovative", jp:["革新的な"], pos:"形容詞", category:"変化" },
  { en:"intellectual", jp:["知的な"], pos:"形容詞", category:"学習" },
  { en:"intense", jp:["強烈な"], pos:"形容詞", category:"感情" },
  { en:"internal", jp:["内部の"], pos:"形容詞", category:"場所" },
  { en:"international", jp:["国際的な"], pos:"形容詞", category:"社会" },
  { en:"involved", jp:["関与している"], pos:"形容詞", category:"状態" },

  { en:"legal", jp:["法律の"], pos:"形容詞", category:"社会" },
  { en:"likely", jp:["ありそうな"], pos:"形容詞", category:"思考" },
  { en:"limited", jp:["限られた"], pos:"形容詞", category:"抽象" },
  { en:"local", jp:["地元の"], pos:"形容詞", category:"場所" },
  { en:"logical", jp:["論理的な"], pos:"形容詞", category:"思考" },
  { en:"lonely", jp:["孤独な"], pos:"形容詞", category:"感情" },
  { en:"long-term", jp:["長期的な"], pos:"形容詞", category:"時間" },

  { en:"major", jp:["主要な"], pos:"形容詞", category:"抽象" },
  { en:"massive", jp:["巨大な"], pos:"形容詞", category:"数字" },
  { en:"medical", jp:["医学の"], pos:"形容詞", category:"学習" },
  { en:"mental", jp:["精神の"], pos:"形容詞", category:"感情" },
  { en:"military", jp:["軍事の"], pos:"形容詞", category:"社会" },
  { en:"minor", jp:["小さい方の"], pos:"形容詞", category:"抽象" },
  { en:"modern", jp:["現代の"], pos:"形容詞", category:"時間" },
  { en:"moral", jp:["道徳的な"], pos:"形容詞", category:"社会" },
  { en:"multiple", jp:["複数の"], pos:"形容詞", category:"数字" },

  { en:"narrow", jp:["狭い"], pos:"形容詞", category:"場所" },
  { en:"native", jp:["母国の","生まれつきの"], pos:"形容詞", category:"人" },
  { en:"negative", jp:["否定的な"], pos:"形容詞", category:"感情" },
  { en:"nervous", jp:["緊張している"], pos:"形容詞", category:"感情" },
  { en:"nuclear", jp:["核の"], pos:"形容詞", category:"学習" },

  { en:"obvious", jp:["明らかな"], pos:"形容詞", category:"思考" },
  { en:"official", jp:["公式の"], pos:"形容詞", category:"社会" },
  { en:"ordinary", jp:["普通の"], pos:"形容詞", category:"抽象" },
  { en:"overall", jp:["全体的な"], pos:"形容詞", category:"抽象" },

  { en:"particular", jp:["特定の"], pos:"形容詞", category:"抽象" },
  { en:"passive", jp:["受け身の"], pos:"形容詞", category:"状態" },
  { en:"patient", jp:["辛抱強い"], pos:"形容詞", category:"感情" },
  { en:"permanent", jp:["永久の"], pos:"形容詞", category:"時間" },
  { en:"physical", jp:["身体の","物理的な"], pos:"形容詞", category:"体" },
  { en:"political", jp:["政治の"], pos:"形容詞", category:"社会" },
  { en:"popular", jp:["人気のある"], pos:"形容詞", category:"社会" },
  { en:"positive", jp:["前向きな","肯定的な"], pos:"形容詞", category:"感情" },
  { en:"potential", jp:["潜在的な"], pos:"形容詞", category:"抽象" },
  { en:"practical", jp:["実用的な"], pos:"形容詞", category:"抽象" },
  { en:"precise", jp:["正確な"], pos:"形容詞", category:"学習" },
  { en:"previous", jp:["以前の"], pos:"形容詞", category:"時間" },
  { en:"primary", jp:["主要な"], pos:"形容詞", category:"抽象" },
  { en:"principal", jp:["主要な"], pos:"形容詞", category:"抽象" },
  { en:"private", jp:["個人の"], pos:"形容詞", category:"社会" },
  { en:"probable", jp:["ありそうな"], pos:"形容詞", category:"思考" },
  { en:"professional", jp:["専門的な"], pos:"形容詞", category:"社会" },
  { en:"proper", jp:["適切な"], pos:"形容詞", category:"抽象" },
  { en:"psychological", jp:["心理的な"], pos:"形容詞", category:"感情" },
  { en:"public", jp:["公の"], pos:"形容詞", category:"社会" },

  { en:"rapid", jp:["急速な"], pos:"形容詞", category:"時間" },
  { en:"rare", jp:["まれな"], pos:"形容詞", category:"抽象" },
  { en:"reasonable", jp:["妥当な"], pos:"形容詞", category:"思考" },
  { en:"recent", jp:["最近の"], pos:"形容詞", category:"時間" },
  { en:"regional", jp:["地域の"], pos:"形容詞", category:"場所" },
  { en:"relative", jp:["相対的な"], pos:"形容詞", category:"抽象" },
  { en:"relevant", jp:["関連のある"], pos:"形容詞", category:"思考" },
  { en:"reliable", jp:["信頼できる"], pos:"形容詞", category:"感情" },
  { en:"remarkable", jp:["注目すべき"], pos:"形容詞", category:"感情" },
  { en:"remote", jp:["遠く離れた"], pos:"形容詞", category:"場所" },
  { en:"representative", jp:["典型的な"], pos:"形容詞", category:"抽象" },
  { en:"responsible", jp:["責任がある"], pos:"形容詞", category:"社会" },
  { en:"rich", jp:["豊かな"], pos:"形容詞", category:"社会" },
  { en:"rural", jp:["田舎の"], pos:"形容詞", category:"場所" },

  { en:"scientific", jp:["科学の"], pos:"形容詞", category:"学習" },
  { en:"secondary", jp:["二次的な"], pos:"形容詞", category:"抽象" },
  { en:"serious", jp:["深刻な"], pos:"形容詞", category:"感情" },
  { en:"similar", jp:["似ている"], pos:"形容詞", category:"抽象" },
  { en:"simple", jp:["単純な"], pos:"形容詞", category:"抽象" },
  { en:"slight", jp:["わずかな"], pos:"形容詞", category:"数字" },
  { en:"social", jp:["社会の"], pos:"形容詞", category:"社会" },
  { en:"specific", jp:["具体的な"], pos:"形容詞", category:"思考" },
  { en:"sensitive", jp:["敏感な"], pos:"形容詞", category:"感情" },
  { en:"severe", jp:["深刻な"], pos:"形容詞", category:"状態" },
  { en:"significant", jp:["重要な","かなりの"], pos:"形容詞", category:"抽象" },
  { en:"sophisticated", jp:["洗練された","高度な"], pos:"形容詞", category:"抽象" },
  { en:"stable", jp:["安定した"], pos:"形容詞", category:"状態" },
  { en:"standard", jp:["標準の"], pos:"形容詞", category:"抽象" },
  { en:"strict", jp:["厳しい"], pos:"形容詞", category:"感情" },
  { en:"sufficient", jp:["十分な"], pos:"形容詞", category:"抽象" },
  { en:"suitable", jp:["適した"], pos:"形容詞", category:"抽象" },

  { en:"technical", jp:["技術的な"], pos:"形容詞", category:"学習" },
  { en:"temporary", jp:["一時的な"], pos:"形容詞", category:"時間" },
  { en:"theoretical", jp:["理論上の"], pos:"形容詞", category:"学習" },
  { en:"typical", jp:["典型的な"], pos:"形容詞", category:"抽象" },

  { en:"unique", jp:["独特の"], pos:"形容詞", category:"抽象" },
  { en:"universal", jp:["普遍的な"], pos:"形容詞", category:"抽象" },
  { en:"urban", jp:["都市の"], pos:"形容詞", category:"場所" },
  { en:"useful", jp:["役に立つ"], pos:"形容詞", category:"抽象" },

  { en:"various", jp:["さまざまな"], pos:"形容詞", category:"抽象" },
  { en:"vital", jp:["極めて重要な"], pos:"形容詞", category:"抽象" },

  { en:"widespread", jp:["広く普及した"], pos:"形容詞", category:"社会" }
];