const words_en_nouns = [
  { en:"access", jp:["利用する権利","接近"], pos:"名詞", category:"社会" },
  { en:"accommodation", jp:["宿泊施設","適応"], pos:"名詞", category:"社会" },
  { en:"accomplishment", jp:["達成","業績"], pos:"名詞", category:"抽象" },
  { en:"accuracy", jp:["正確さ"], pos:"名詞", category:"学習" },
  { en:"administration", jp:["管理","行政"], pos:"名詞", category:"社会" },
  { en:"admission", jp:["入場","入学","承認"], pos:"名詞", category:"社会" },
  { en:"affair", jp:["出来事","情勢"], pos:"名詞", category:"社会" },
  { en:"agency", jp:["機関","代理店"], pos:"名詞", category:"社会" },
  { en:"agriculture", jp:["農業"], pos:"名詞", category:"社会" },
  { en:"alternative", jp:["代替案"], pos:"名詞", category:"抽象" },
  { en:"ambition", jp:["野心","大きな目標"], pos:"名詞", category:"感情" },
  { en:"ancestor", jp:["祖先"], pos:"名詞", category:"人" },
  { en:"anniversary", jp:["記念日"], pos:"名詞", category:"時間" },
  { en:"anticipation", jp:["予期","期待"], pos:"名詞", category:"感情" },
  { en:"anxiety", jp:["不安"], pos:"名詞", category:"感情" },
  { en:"appetite", jp:["食欲"], pos:"名詞", category:"体" },
  { en:"argument", jp:["議論","主張"], pos:"名詞", category:"会話" },
  { en:"association", jp:["協会","関連"], pos:"名詞", category:"社会" },
  { en:"assumption", jp:["仮定"], pos:"名詞", category:"思考" },
  { en:"atmosphere", jp:["雰囲気","大気"], pos:"名詞", category:"自然" },

  { en:"boundary", jp:["境界"], pos:"名詞", category:"場所" },
  { en:"budget", jp:["予算"], pos:"名詞", category:"社会" },
  { en:"burden", jp:["負担"], pos:"名詞", category:"抽象" },

  { en:"capacity", jp:["能力","収容力"], pos:"名詞", category:"抽象" },
  { en:"circumstance", jp:["状況","事情"], pos:"名詞", category:"抽象" },
  { en:"civilization", jp:["文明"], pos:"名詞", category:"社会" },
  { en:"colleague", jp:["同僚"], pos:"名詞", category:"人" },
  { en:"commitment", jp:["責任","献身"], pos:"名詞", category:"社会" },
  { en:"comparison", jp:["比較"], pos:"名詞", category:"学習" },
  { en:"competition", jp:["競争"], pos:"名詞", category:"社会" },
  { en:"complaint", jp:["苦情","不満"], pos:"名詞", category:"会話" },
  { en:"complication", jp:["複雑化","厄介な問題"], pos:"名詞", category:"抽象" },
  { en:"component", jp:["構成要素"], pos:"名詞", category:"学習" },
  { en:"concentration", jp:["集中","濃度"], pos:"名詞", category:"思考" },
  { en:"conclusion", jp:["結論"], pos:"名詞", category:"思考" },
  { en:"condition", jp:["状態","条件"], pos:"名詞", category:"抽象" },
  { en:"consequence", jp:["結果"], pos:"名詞", category:"変化" },
  { en:"conservation", jp:["保護","保存"], pos:"名詞", category:"自然" },
  { en:"construction", jp:["建設","構造"], pos:"名詞", category:"社会" },
  { en:"consumption", jp:["消費"], pos:"名詞", category:"社会" },
  { en:"contact", jp:["接触","連絡"], pos:"名詞", category:"会話" },
  { en:"contribution", jp:["貢献","寄付"], pos:"名詞", category:"社会" },
  { en:"controversy", jp:["論争"], pos:"名詞", category:"会話" },
  { en:"convention", jp:["慣習","大会"], pos:"名詞", category:"社会" },
  { en:"cooperation", jp:["協力"], pos:"名詞", category:"社会" },
  { en:"corporation", jp:["企業"], pos:"名詞", category:"社会" },
  { en:"correspondence", jp:["一致","通信"], pos:"名詞", category:"会話" },
  { en:"coverage", jp:["報道","範囲"], pos:"名詞", category:"社会" },
  { en:"criterion", jp:["基準"], pos:"名詞", category:"学習" },
  { en:"curiosity", jp:["好奇心"], pos:"名詞", category:"感情" },

  { en:"decade", jp:["10年間"], pos:"名詞", category:"時間" },
  { en:"decline", jp:["減少","衰退"], pos:"名詞", category:"変化" },
  { en:"deficit", jp:["不足","赤字"], pos:"名詞", category:"社会" },
  { en:"definition", jp:["定義"], pos:"名詞", category:"学習" },
  { en:"democracy", jp:["民主主義"], pos:"名詞", category:"社会" },
  { en:"departure", jp:["出発"], pos:"名詞", category:"移動" },
  { en:"dependence", jp:["依存"], pos:"名詞", category:"状態" },
  { en:"depression", jp:["不況","落ち込み"], pos:"名詞", category:"社会" },
  { en:"destination", jp:["目的地"], pos:"名詞", category:"場所" },
  { en:"destruction", jp:["破壊"], pos:"名詞", category:"変化" },
  { en:"detail", jp:["詳細"], pos:"名詞", category:"学習" },
  { en:"device", jp:["装置"], pos:"名詞", category:"物" },
  { en:"dignity", jp:["尊厳"], pos:"名詞", category:"感情" },
  { en:"dimension", jp:["側面","次元"], pos:"名詞", category:"学習" },
  { en:"disadvantage", jp:["不利","欠点"], pos:"名詞", category:"抽象" },
  { en:"discipline", jp:["規律","学問分野"], pos:"名詞", category:"学習" },
  { en:"dispute", jp:["論争"], pos:"名詞", category:"会話" },
  { en:"distinction", jp:["区別"], pos:"名詞", category:"学習" },
  { en:"distribution", jp:["分配","流通"], pos:"名詞", category:"社会" },
  { en:"diversity", jp:["多様性"], pos:"名詞", category:"社会" },

  { en:"economics", jp:["経済学"], pos:"名詞", category:"学習" },
  { en:"efficiency", jp:["効率"], pos:"名詞", category:"抽象" },
  { en:"element", jp:["要素"], pos:"名詞", category:"学習" },
  { en:"emphasis", jp:["強調"], pos:"名詞", category:"会話" },
  { en:"encounter", jp:["遭遇"], pos:"名詞", category:"行動" },
  { en:"enterprise", jp:["企業","事業"], pos:"名詞", category:"社会" },
  { en:"enthusiasm", jp:["熱意"], pos:"名詞", category:"感情" },
  { en:"equivalent", jp:["同等のもの"], pos:"名詞", category:"学習" },
  { en:"estimate", jp:["見積もり","評価"], pos:"名詞", category:"学習" },
  { en:"ethics", jp:["倫理"], pos:"名詞", category:"社会" },
  { en:"evidence", jp:["証拠"], pos:"名詞", category:"学習" },
  { en:"evolution", jp:["進化"], pos:"名詞", category:"変化" },
  { en:"exception", jp:["例外"], pos:"名詞", category:"抽象" },
  { en:"exposure", jp:["さらされること","露出"], pos:"名詞", category:"状態" },
  { en:"extension", jp:["拡張","延長"], pos:"名詞", category:"変化" },

  { en:"facility", jp:["施設"], pos:"名詞", category:"場所" },
  { en:"factor", jp:["要因"], pos:"名詞", category:"抽象" },
  { en:"faculty", jp:["能力","学部"], pos:"名詞", category:"学習" },
  { en:"famine", jp:["飢饉"], pos:"名詞", category:"社会" },
  { en:"foundation", jp:["基礎","財団"], pos:"名詞", category:"抽象" },
  { en:"framework", jp:["枠組み"], pos:"名詞", category:"学習" },
  { en:"function", jp:["機能"], pos:"名詞", category:"学習" },

  { en:"gene", jp:["遺伝子"], pos:"名詞", category:"学習" },
  { en:"generation", jp:["世代"], pos:"名詞", category:"時間" },
  { en:"goal", jp:["目標"], pos:"名詞", category:"感情" },
  { en:"guideline", jp:["指針"], pos:"名詞", category:"社会" },

  { en:"hardship", jp:["苦難"], pos:"名詞", category:"状態" },
  { en:"heritage", jp:["遺産"], pos:"名詞", category:"社会" },
  { en:"hypothesis", jp:["仮説"], pos:"名詞", category:"学習" },

  { en:"impact", jp:["影響"], pos:"名詞", category:"変化" },
  { en:"implication", jp:["含意","影響"], pos:"名詞", category:"思考" },
  { en:"income", jp:["収入"], pos:"名詞", category:"社会" },
  { en:"independence", jp:["独立"], pos:"名詞", category:"社会" },
  { en:"indicator", jp:["指標"], pos:"名詞", category:"学習" },
  { en:"inequality", jp:["不平等"], pos:"名詞", category:"社会" },
  { en:"infection", jp:["感染"], pos:"名詞", category:"体" },
  { en:"influence", jp:["影響"], pos:"名詞", category:"変化" },
  { en:"initiative", jp:["主導権","新構想"], pos:"名詞", category:"社会" },
  { en:"innovation", jp:["革新"], pos:"名詞", category:"変化" },
  { en:"insight", jp:["洞察"], pos:"名詞", category:"思考" },
  { en:"institution", jp:["機関","制度"], pos:"名詞", category:"社会" },
  { en:"interaction", jp:["相互作用"], pos:"名詞", category:"社会" },
  { en:"interpretation", jp:["解釈"], pos:"名詞", category:"思考" },
  { en:"intervention", jp:["介入"], pos:"名詞", category:"社会" },
  { en:"investment", jp:["投資"], pos:"名詞", category:"社会" },
  { en:"issue", jp:["問題"], pos:"名詞", category:"社会" },

  { en:"justice", jp:["正義"], pos:"名詞", category:"社会" },

  { en:"landscape", jp:["風景"], pos:"名詞", category:"自然" },
  { en:"legacy", jp:["遺産"], pos:"名詞", category:"社会" },
  { en:"liberty", jp:["自由"], pos:"名詞", category:"社会" },
  { en:"literacy", jp:["読み書き能力"], pos:"名詞", category:"学習" },

  { en:"maintenance", jp:["維持","保守"], pos:"名詞", category:"状態" },
  { en:"majority", jp:["大多数"], pos:"名詞", category:"数字" },
  { en:"mechanism", jp:["仕組み"], pos:"名詞", category:"学習" },
  { en:"migration", jp:["移住"], pos:"名詞", category:"移動" },
  { en:"minority", jp:["少数"], pos:"名詞", category:"数字" },
  { en:"mission", jp:["使命"], pos:"名詞", category:"感情" },
  { en:"motivation", jp:["動機"], pos:"名詞", category:"感情" },

  { en:"norm", jp:["規範"], pos:"名詞", category:"社会" },
  { en:"notion", jp:["考え"], pos:"名詞", category:"思考" },

  { en:"objective", jp:["目的"], pos:"名詞", category:"感情" },
  { en:"obligation", jp:["義務"], pos:"名詞", category:"社会" },
  { en:"observation", jp:["観察"], pos:"名詞", category:"学習" },
  { en:"obstacle", jp:["障害"], pos:"名詞", category:"抽象" },
  { en:"occasion", jp:["機会"], pos:"名詞", category:"時間" },
  { en:"occupation", jp:["職業"], pos:"名詞", category:"社会" },
  { en:"outcome", jp:["結果"], pos:"名詞", category:"変化" },

  { en:"perspective", jp:["視点"], pos:"名詞", category:"思考" },
  { en:"phenomenon", jp:["現象"], pos:"名詞", category:"学習" },
  { en:"policy", jp:["政策"], pos:"名詞", category:"社会" },
  { en:"poverty", jp:["貧困"], pos:"名詞", category:"社会" },
  { en:"prejudice", jp:["偏見"], pos:"名詞", category:"感情" },
  { en:"priority", jp:["優先事項"], pos:"名詞", category:"抽象" },
  { en:"procedure", jp:["手順"], pos:"名詞", category:"学習" },
  { en:"process", jp:["過程"], pos:"名詞", category:"変化" },
  { en:"prospect", jp:["見通し"], pos:"名詞", category:"思考" },
  { en:"protein", jp:["たんぱく質"], pos:"名詞", category:"体" },

  { en:"range", jp:["範囲"], pos:"名詞", category:"抽象" },
  { en:"reduction", jp:["減少"], pos:"名詞", category:"変化" },
  { en:"reference", jp:["言及","参照"], pos:"名詞", category:"会話" },
  { en:"reflection", jp:["反映","熟考"], pos:"名詞", category:"思考" },
  { en:"reform", jp:["改革"], pos:"名詞", category:"社会" },
  { en:"region", jp:["地域"], pos:"名詞", category:"場所" },
  { en:"regulation", jp:["規制"], pos:"名詞", category:"社会" },
  { en:"reputation", jp:["評判"], pos:"名詞", category:"社会" },
  { en:"requirement", jp:["必要条件"], pos:"名詞", category:"抽象" },
  { en:"resource", jp:["資源"], pos:"名詞", category:"社会" },
  { en:"restriction", jp:["制限"], pos:"名詞", category:"社会" },
  { en:"revenue", jp:["収益"], pos:"名詞", category:"社会" },
  { en:"routine", jp:["日課"], pos:"名詞", category:"時間" },

  { en:"scholar", jp:["学者"], pos:"名詞", category:"人" },
  { en:"sector", jp:["部門"], pos:"名詞", category:"社会" },
  { en:"sequence", jp:["連続","順序"], pos:"名詞", category:"時間" },
  { en:"shortage", jp:["不足"], pos:"名詞", category:"状態" },
  { en:"significance", jp:["重要性"], pos:"名詞", category:"抽象" },
  { en:"strategy", jp:["戦略"], pos:"名詞", category:"思考" },
  { en:"substance", jp:["物質","本質"], pos:"名詞", category:"学習" },
  { en:"supply", jp:["供給"], pos:"名詞", category:"社会" },
  { en:"surface", jp:["表面"], pos:"名詞", category:"物" },

  { en:"task", jp:["課題"], pos:"名詞", category:"学習" },
  { en:"technique", jp:["技術"], pos:"名詞", category:"学習" },
  { en:"tendency", jp:["傾向"], pos:"名詞", category:"思考" },
  { en:"term", jp:["用語","期間"], pos:"名詞", category:"学習" },
  { en:"territory", jp:["領土"], pos:"名詞", category:"場所" },
  { en:"theory", jp:["理論"], pos:"名詞", category:"学習" },
  { en:"threat", jp:["脅威"], pos:"名詞", category:"状態" },
  { en:"transition", jp:["移行"], pos:"名詞", category:"変化" },
  { en:"trend", jp:["傾向"], pos:"名詞", category:"変化" },

  { en:"union", jp:["統合","組合"], pos:"名詞", category:"社会" },
  { en:"utility", jp:["有用性","公共事業"], pos:"名詞", category:"抽象" },

  { en:"variation", jp:["変化","変種"], pos:"名詞", category:"変化" },
  { en:"vehicle", jp:["乗り物"], pos:"名詞", category:"交通" },
  { en:"victim", jp:["犠牲者"], pos:"名詞", category:"人" },
  { en:"violence", jp:["暴力"], pos:"名詞", category:"社会" },
  { en:"vision", jp:["視野","構想"], pos:"名詞", category:"思考" },
  { en:"volume", jp:["量"], pos:"名詞", category:"数字" },

  { en:"welfare", jp:["福祉"], pos:"名詞", category:"社会" },
  { en:"withdrawal", jp:["撤退","引き出し"], pos:"名詞", category:"行動" }
];