const words_de_adjectives = [
  { de:"alt", en:["old"], jp:["古い","年を取った"], pos:"形容詞", category:"時間" },
  { de:"anders", en:["different"], jp:["違う"], pos:"形容詞", category:"抽象" },
  { de:"angenehm", en:["pleasant"], jp:["心地よい"], pos:"形容詞", category:"感情" },
  { de:"anstrengend", en:["tiring"], jp:["疲れる"], pos:"形容詞", category:"体" },
  { de:"arm", en:["poor"], jp:["貧しい"], pos:"形容詞", category:"社会" },
  { de:"attraktiv", en:["attractive"], jp:["魅力的な"], pos:"形容詞", category:"感情" },
  { de:"ausgezeichnet", en:["excellent"], jp:["素晴らしい"], pos:"形容詞", category:"抽象" },
  { de:"ausländisch", en:["foreign"], jp:["外国の"], pos:"形容詞", category:"場所" },

  { de:"bequem", en:["comfortable"], jp:["快適な"], pos:"形容詞", category:"状態" },
  { de:"berühmt", en:["famous"], jp:["有名な"], pos:"形容詞", category:"社会" },
  { de:"besonders", en:["special"], jp:["特別な"], pos:"形容詞", category:"抽象" },
  { de:"besser", en:["better"], jp:["より良い"], pos:"形容詞", category:"抽象" },
  { de:"bitter", en:["bitter"], jp:["苦い"], pos:"形容詞", category:"食べ物・飲み物" },
  { de:"blind", en:["blind"], jp:["目の見えない"], pos:"形容詞", category:"体" },
  { de:"blond", en:["blond"], jp:["金髪の"], pos:"形容詞", category:"体" },
  { de:"blöd", en:["stupid"], jp:["ばかな"], pos:"形容詞", category:"感情" },
  { de:"böse", en:["angry","bad"], jp:["怒った","悪い"], pos:"形容詞", category:"感情" },
  { de:"breit", en:["wide"], jp:["幅広い"], pos:"形容詞", category:"場所" },
  { de:"brav", en:["well-behaved"], jp:["お利口な"], pos:"形容詞", category:"感情" },
  { de:"braun", en:["brown"], jp:["茶色の"], pos:"形容詞", category:"色" },
  { de:"busy", en:["busy"], jp:["忙しい"], pos:"形容詞", category:"状態" },

  { de:"chaotisch", en:["chaotic"], jp:["混乱した"], pos:"形容詞", category:"状態" },
  { de:"cool", en:["cool"], jp:["かっこいい"], pos:"形容詞", category:"感情" },

  { de:"deutlich", en:["clear"], jp:["明らかな"], pos:"形容詞", category:"抽象" },
  { de:"deutsch", en:["German"], jp:["ドイツの"], pos:"形容詞", category:"場所" },
  { de:"dick", en:["thick","fat"], jp:["厚い","太った"], pos:"形容詞", category:"体" },
  { de:"direkt", en:["direct"], jp:["直接の"], pos:"形容詞", category:"抽象" },
  { de:"dumm", en:["stupid"], jp:["頭が悪い"], pos:"形容詞", category:"感情" },
  { de:"dunkel", en:["dark"], jp:["暗い"], pos:"形容詞", category:"状態" },
  { de:"durstig", en:["thirsty"], jp:["のどが渇いた"], pos:"形容詞", category:"体" },

  { de:"ehrlich", en:["honest"], jp:["正直な"], pos:"形容詞", category:"感情" },
  { de:"einfach", en:["easy","simple"], jp:["簡単な"], pos:"形容詞", category:"抽象" },
  { de:"elegant", en:["elegant"], jp:["上品な"], pos:"形容詞", category:"感情" },
  { de:"eng", en:["narrow"], jp:["狭い"], pos:"形容詞", category:"場所" },
  { de:"ernst", en:["serious"], jp:["まじめな"], pos:"形容詞", category:"感情" },
  { de:"erquicklich", en:["refreshing"], jp:["さわやかな"], pos:"形容詞", category:"感情" },

  { de:"falsch", en:["wrong","false"], jp:["間違った"], pos:"形容詞", category:"抽象" },
  { de:"fantastisch", en:["fantastic"], jp:["素晴らしい"], pos:"形容詞", category:"感情" },
  { de:"faul", en:["lazy"], jp:["怠け者の"], pos:"形容詞", category:"感情" },
  { de:"fein", en:["fine","delicate"], jp:["上質な","細かい"], pos:"形容詞", category:"抽象" },
  { de:"fertig", en:["finished","ready"], jp:["準備ができた","終わった"], pos:"形容詞", category:"状態" },
  { de:"fest", en:["firm","solid"], jp:["固い"], pos:"形容詞", category:"状態" },
  { de:"feucht", en:["moist"], jp:["湿った"], pos:"形容詞", category:"状態" },
  { de:"fleißig", en:["hard-working"], jp:["勤勉な"], pos:"形容詞", category:"感情" },
  { de:"frei", en:["free"], jp:["自由な","空いている"], pos:"形容詞", category:"状態" },
  { de:"freundlich", en:["friendly"], jp:["親切な"], pos:"形容詞", category:"感情" },
  { de:"frisch", en:["fresh"], jp:["新鮮な"], pos:"形容詞", category:"食べ物・飲み物" },
  { de:"fröhlich", en:["cheerful"], jp:["陽気な"], pos:"形容詞", category:"感情" },
  { de:"früh", en:["early"], jp:["早い"], pos:"形容詞", category:"時間" },
  { de:"furchtbar", en:["terrible"], jp:["ひどい"], pos:"形容詞", category:"感情" },

  { de:"ganz", en:["whole","entire"], jp:["全部の"], pos:"形容詞", category:"抽象" },
  { de:"geduldig", en:["patient"], jp:["辛抱強い"], pos:"形容詞", category:"感情" },
  { de:"gefährlich", en:["dangerous"], jp:["危険な"], pos:"形容詞", category:"状態" },
  { de:"gemütlich", en:["cozy"], jp:["居心地のよい"], pos:"形容詞", category:"状態" },
  { de:"genau", en:["exact","precise"], jp:["正確な"], pos:"形容詞", category:"学習" },
  { de:"genug", en:["enough"], jp:["十分な"], pos:"形容詞", category:"抽象" },
  { de:"gesund", en:["healthy"], jp:["健康な"], pos:"形容詞", category:"体" },
  { de:"glücklich", en:["happy"], jp:["幸せな"], pos:"形容詞", category:"感情" },
  { de:"golden", en:["golden"], jp:["金色の"], pos:"形容詞", category:"色" },
  { de:"groß", en:["big","tall"], jp:["大きい","背が高い"], pos:"形容詞", category:"場所" },
  { de:"gut", en:["good"], jp:["良い"], pos:"形容詞", category:"抽象" },
  { de:"günstig", en:["cheap","favorable"], jp:["安い","都合のよい"], pos:"形容詞", category:"社会" },

  { de:"hässlich", en:["ugly"], jp:["醜い"], pos:"形容詞", category:"感情" },
  { de:"hart", en:["hard"], jp:["硬い","厳しい"], pos:"形容詞", category:"状態" },
  { de:"heiß", en:["hot"], jp:["熱い","暑い"], pos:"形容詞", category:"温度" },
  { de:"hell", en:["bright"], jp:["明るい"], pos:"形容詞", category:"状態" },
  { de:"hilfreich", en:["helpful"], jp:["役に立つ"], pos:"形容詞", category:"抽象" },
  { de:"hoch", en:["high","tall"], jp:["高い"], pos:"形容詞", category:"場所" },
  { de:"höflich", en:["polite"], jp:["礼儀正しい"], pos:"形容詞", category:"感情" },
  { de:"hungrig", en:["hungry"], jp:["お腹がすいた"], pos:"形容詞", category:"体" },

  { de:"interessant", en:["interesting"], jp:["興味深い"], pos:"形容詞", category:"感情" },
  { de:"jung", en:["young"], jp:["若い"], pos:"形容詞", category:"時間" },

  { de:"kalt", en:["cold"], jp:["冷たい","寒い"], pos:"形容詞", category:"温度" },
  { de:"kaputt", en:["broken"], jp:["壊れた"], pos:"形容詞", category:"状態" },
  { de:"klar", en:["clear"], jp:["明確な"], pos:"形容詞", category:"思考" },
  { de:"klein", en:["small"], jp:["小さい"], pos:"形容詞", category:"場所" },
  { de:"klug", en:["smart","clever"], jp:["賢い"], pos:"形容詞", category:"思考" },
  { de:"komisch", en:["strange","funny"], jp:["変な","おかしい"], pos:"形容詞", category:"感情" },
  { de:"krank", en:["sick"], jp:["病気の"], pos:"形容詞", category:"体" },
  { de:"kreativ", en:["creative"], jp:["創造的な"], pos:"形容詞", category:"芸術" },
  { de:"kurz", en:["short"], jp:["短い"], pos:"形容詞", category:"時間" },

  { de:"lang", en:["long"], jp:["長い"], pos:"形容詞", category:"時間" },
  { de:"langweilig", en:["boring"], jp:["退屈な"], pos:"形容詞", category:"感情" },
  { de:"langsam", en:["slow"], jp:["遅い"], pos:"形容詞", category:"時間" },
  { de:"laut", en:["loud"], jp:["うるさい"], pos:"形容詞", category:"状態" },
  { de:"leer", en:["empty"], jp:["空の"], pos:"形容詞", category:"状態" },
  { de:"leicht", en:["light","easy"], jp:["軽い","簡単な"], pos:"形容詞", category:"抽象" },
  { de:"leise", en:["quiet"], jp:["静かな"], pos:"形容詞", category:"状態" },
  { de:"lieb", en:["dear","kind"], jp:["やさしい","親しい"], pos:"形容詞", category:"感情" },
  { de:"lokal", en:["local"], jp:["地元の"], pos:"形容詞", category:"場所" },
  { de:"lustig", en:["funny","cheerful"], jp:["おかしい","楽しい"], pos:"形容詞", category:"感情" },

  { de:"möglich", en:["possible"], jp:["可能な"], pos:"形容詞", category:"抽象" },
  { de:"müde", en:["tired"], jp:["疲れた"], pos:"形容詞", category:"体" },
  { de:"modern", en:["modern"], jp:["現代的な"], pos:"形容詞", category:"時間" },

  { de:"nah", en:["near"], jp:["近い"], pos:"形容詞", category:"場所" },
  { de:"nass", en:["wet"], jp:["ぬれた"], pos:"形容詞", category:"状態" },
  { de:"natürlich", en:["natural","of course"], jp:["自然な","もちろん"], pos:"形容詞", category:"自然" },
  { de:"neblig", en:["foggy"], jp:["霧の多い"], pos:"形容詞", category:"自然" },
  { de:"negativ", en:["negative"], jp:["否定的な"], pos:"形容詞", category:"感情" },
  { de:"nervös", en:["nervous"], jp:["緊張した"], pos:"形容詞", category:"感情" },
  { de:"nett", en:["nice"], jp:["親切な"], pos:"形容詞", category:"感情" },
  { de:"neu", en:["new"], jp:["新しい"], pos:"形容詞", category:"時間" },
  { de:"niedrig", en:["low"], jp:["低い"], pos:"形容詞", category:"場所" },
  { de:"nützlich", en:["useful"], jp:["役に立つ"], pos:"形容詞", category:"抽象" },

  { de:"offen", en:["open"], jp:["開いている"], pos:"形容詞", category:"状態" },
  { de:"offiziell", en:["official"], jp:["公式の"], pos:"形容詞", category:"社会" },
  { de:"ordentlich", en:["tidy","proper"], jp:["きちんとした"], pos:"形容詞", category:"状態" },

  { de:"persönlich", en:["personal"], jp:["個人的な"], pos:"形容詞", category:"人" },
  { de:"positiv", en:["positive"], jp:["肯定的な"], pos:"形容詞", category:"感情" },
  { de:"praktisch", en:["practical"], jp:["実用的な"], pos:"形容詞", category:"抽象" },
  { de:"pünktlich", en:["punctual","on time"], jp:["時間どおりの"], pos:"形容詞", category:"時間" },

  { de:"reich", en:["rich"], jp:["裕福な"], pos:"形容詞", category:"社会" },
  { de:"reif", en:["ripe","mature"], jp:["熟した","成熟した"], pos:"形容詞", category:"食べ物・飲み物" },
  { de:"richtig", en:["correct","right"], jp:["正しい"], pos:"形容詞", category:"学習" },
  { de:"ruhig", en:["calm","quiet"], jp:["落ち着いた","静かな"], pos:"形容詞", category:"感情" },
  { de:"rot", en:["red"], jp:["赤い"], pos:"形容詞", category:"色" },

  { de:"sauber", en:["clean"], jp:["きれいな"], pos:"形容詞", category:"状態" },
  { de:"schade", en:["a pity"], jp:["残念な"], pos:"形容詞", category:"感情" },
  { de:"schlecht", en:["bad"], jp:["悪い"], pos:"形容詞", category:"抽象" },
  { de:"schmal", en:["narrow"], jp:["細い","狭い"], pos:"形容詞", category:"場所" },
  { de:"schnell", en:["fast","quick"], jp:["速い"], pos:"形容詞", category:"時間" },
  { de:"schön", en:["beautiful","nice"], jp:["美しい","すてきな"], pos:"形容詞", category:"感情" },
  { de:"schrecklich", en:["terrible"], jp:["ひどい"], pos:"形容詞", category:"感情" },
  { de:"schwierig", en:["difficult"], jp:["難しい"], pos:"形容詞", category:"学習" },
  { de:"schwach", en:["weak"], jp:["弱い"], pos:"形容詞", category:"体" },
  { de:"schwarz", en:["black"], jp:["黒い"], pos:"形容詞", category:"色" },
  { de:"selbstständig", en:["independent"], jp:["自立した"], pos:"形容詞", category:"感情" },
  { de:"selten", en:["rare"], jp:["まれな"], pos:"形容詞", category:"時間" },
  { de:"sicher", en:["safe","sure"], jp:["安全な","確かな"], pos:"形容詞", category:"状態" },
  { de:"silbern", en:["silver"], jp:["銀色の"], pos:"形容詞", category:"色" },
  { de:"spannend", en:["exciting"], jp:["わくわくする"], pos:"形容詞", category:"感情" },
  { de:"spät", en:["late"], jp:["遅い"], pos:"形容詞", category:"時間" },
  { de:"sportlich", en:["sporty","athletic"], jp:["運動好きな"], pos:"形容詞", category:"体" },
  { de:"stark", en:["strong"], jp:["強い"], pos:"形容詞", category:"体" },
  { de:"still", en:["silent","quiet"], jp:["静かな"], pos:"形容詞", category:"状態" },
  { de:"streng", en:["strict"], jp:["厳しい"], pos:"形容詞", category:"感情" },
  { de:"sympathisch", en:["pleasant","likeable"], jp:["感じのよい"], pos:"形容詞", category:"感情" },
  { de:"süß", en:["sweet","cute"], jp:["甘い","かわいい"], pos:"形容詞", category:"食べ物・飲み物" },

  { de:"teuer", en:["expensive"], jp:["高価な"], pos:"形容詞", category:"社会" },
  { de:"tot", en:["dead"], jp:["死んでいる"], pos:"形容詞", category:"体" },
  { de:"traurig", en:["sad"], jp:["悲しい"], pos:"形容詞", category:"感情" },
  { de:"trocken", en:["dry"], jp:["乾いた"], pos:"形容詞", category:"状態" },

  { de:"typisch", en:["typical"], jp:["典型的な"], pos:"形容詞", category:"抽象" },

  { de:"unbekannt", en:["unknown"], jp:["知られていない"], pos:"形容詞", category:"思考" },
  { de:"unglaublich", en:["incredible"], jp:["信じられない"], pos:"形容詞", category:"感情" },
  { de:"ungeduldig", en:["impatient"], jp:["せっかちな"], pos:"形容詞", category:"感情" },
  { de:"unhöflich", en:["impolite"], jp:["失礼な"], pos:"形容詞", category:"感情" },
  { de:"unmöglich", en:["impossible"], jp:["不可能な"], pos:"形容詞", category:"抽象" },
  { de:"unruhig", en:["restless"], jp:["落ち着かない"], pos:"形容詞", category:"感情" },
  { de:"unsicher", en:["uncertain","unsafe"], jp:["不確かな","不安な"], pos:"形容詞", category:"感情" },
  { de:"unterschiedlich", en:["different"], jp:["異なる"], pos:"形容詞", category:"抽象" },
  { de:"unwichtig", en:["unimportant"], jp:["重要でない"], pos:"形容詞", category:"抽象" },

  { de:"verheiratet", en:["married"], jp:["結婚している"], pos:"形容詞", category:"人" },
  { de:"verrückt", en:["crazy"], jp:["変な","夢中の"], pos:"形容詞", category:"感情" },
  { de:"verschieden", en:["various","different"], jp:["さまざまな"], pos:"形容詞", category:"抽象" },
  { de:"vorsichtig", en:["careful"], jp:["注意深い"], pos:"形容詞", category:"感情" },

  { de:"wahr", en:["true"], jp:["本当の"], pos:"形容詞", category:"思考" },
  { de:"warm", en:["warm"], jp:["暖かい"], pos:"形容詞", category:"温度" },
  { de:"weich", en:["soft"], jp:["柔らかい"], pos:"形容詞", category:"状態" },
  { de:"weiß", en:["white"], jp:["白い"], pos:"形容詞", category:"色" },
  { de:"wichtig", en:["important"], jp:["重要な"], pos:"形容詞", category:"抽象" },
  { de:"windig", en:["windy"], jp:["風の強い"], pos:"形容詞", category:"自然" },

  { de:"zufrieden", en:["satisfied"], jp:["満足した"], pos:"形容詞", category:"感情" },
  { de:"zusätzlich", en:["additional"], jp:["追加の"], pos:"形容詞", category:"抽象" }
];